/* Generated by tools/gen_eink_fonts.py -- do not edit.
 * Terminus Medium 16 px (ter-u16n.bdf), 1 bpp, standing in
 * as lv_font_montserrat_16 on the T-Deck Pro's e-paper; line metrics
 * 18/5 (Montserrat's were 18/3). Icons fall back to
 * lv_font_eink_symbols_16.
 * Terminus Font: Copyright (C) 2020 Dimitar Toshkov Zhekov, SIL OFL 1.1
 * (see OFL-Terminus.txt). */

#include <lvgl.h>

LV_FONT_DECLARE(lv_font_eink_symbols_16)

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */
    /* U+0021 "!" */
    0xfe, 0xc0,
    /* U+0022 "\"" */
    0x99, 0x90,
    /* U+0023 "#" */
    0x49, 0x24, 0xbf, 0x49, 0x2f, 0xd2, 0x49, 0x20,
    /* U+0024 "$" */
    0x10, 0x21, 0xf4, 0x99, 0x12, 0x1f, 0x09, 0x13, 0x25, 0xf0, 0x81, 0x00,
    /* U+0025 "%" */
    0x65, 0x29, 0xa0, 0x41, 0x02, 0x08, 0x16, 0x52, 0x98,
    /* U+0026 "&" */
    0x31, 0x24, 0x8c, 0x62, 0x58, 0xa2, 0x89, 0xd0,
    /* U+0027 "'" */
    0xe0,
    /* U+0028 "(" */
    0x2a, 0x49, 0x24, 0x44,
    /* U+0029 ")" */
    0x88, 0x92, 0x49, 0x50,
    /* U+002A "*" */
    0x48, 0xcf, 0xcc, 0x48,
    /* U+002B "+" */
    0x21, 0x3e, 0x42, 0x00,
    /* U+002C "," */
    0x58,
    /* U+002D "-" */
    0xfc,
    /* U+002E "." */
    0xc0,
    /* U+002F "/" */
    0x08, 0x44, 0x22, 0x11, 0x08, 0x84, 0x00,
    /* U+0030 "0" */
    0x7a, 0x18, 0x63, 0x96, 0x9c, 0x61, 0x85, 0xe0,
    /* U+0031 "1" */
    0x23, 0x28, 0x42, 0x10, 0x84, 0x27, 0xc0,
    /* U+0032 "2" */
    0x7a, 0x18, 0x41, 0x08, 0x42, 0x10, 0x83, 0xf0,
    /* U+0033 "3" */
    0x7a, 0x18, 0x41, 0x38, 0x10, 0x61, 0x85, 0xe0,
    /* U+0034 "4" */
    0x04, 0x31, 0x49, 0x46, 0x1f, 0xc1, 0x04, 0x10,
    /* U+0035 "5" */
    0xfe, 0x08, 0x20, 0xf8, 0x10, 0x41, 0x85, 0xe0,
    /* U+0036 "6" */
    0x39, 0x08, 0x20, 0xfa, 0x18, 0x61, 0x85, 0xe0,
    /* U+0037 "7" */
    0xfc, 0x10, 0x42, 0x08, 0x41, 0x08, 0x20, 0x80,
    /* U+0038 "8" */
    0x7a, 0x18, 0x61, 0x7a, 0x18, 0x61, 0x85, 0xe0,
    /* U+0039 "9" */
    0x7a, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x09, 0xc0,
    /* U+003A ":" */
    0xc6,
    /* U+003B ";" */
    0x50, 0x16,
    /* U+003C "<" */
    0x08, 0x88, 0x88, 0x20, 0x82, 0x08,
    /* U+003D "=" */
    0xfc, 0x00, 0x3f,
    /* U+003E ">" */
    0x82, 0x08, 0x20, 0x88, 0x88, 0x80,
    /* U+003F "?" */
    0x7a, 0x18, 0x61, 0x08, 0x41, 0x00, 0x10, 0x40,
    /* U+0040 "@" */
    0x7d, 0x06, 0x7d, 0x1a, 0x34, 0x69, 0xcd, 0x80, 0xfc,
    /* U+0041 "A" */
    0x7a, 0x18, 0x61, 0x87, 0xf8, 0x61, 0x86, 0x10,
    /* U+0042 "B" */
    0xfa, 0x18, 0x61, 0xfa, 0x18, 0x61, 0x87, 0xe0,
    /* U+0043 "C" */
    0x7a, 0x18, 0x60, 0x82, 0x08, 0x21, 0x85, 0xe0,
    /* U+0044 "D" */
    0xf2, 0x28, 0x61, 0x86, 0x18, 0x61, 0x8b, 0xc0,
    /* U+0045 "E" */
    0xfe, 0x08, 0x20, 0xf2, 0x08, 0x20, 0x83, 0xf0,
    /* U+0046 "F" */
    0xfe, 0x08, 0x20, 0xf2, 0x08, 0x20, 0x82, 0x00,
    /* U+0047 "G" */
    0x7a, 0x18, 0x60, 0x82, 0x78, 0x61, 0x85, 0xe0,
    /* U+0048 "H" */
    0x86, 0x18, 0x61, 0xfe, 0x18, 0x61, 0x86, 0x10,
    /* U+0049 "I" */
    0xe9, 0x24, 0x92, 0x5c,
    /* U+004A "J" */
    0x1c, 0x20, 0x82, 0x08, 0x20, 0xa2, 0x89, 0xc0,
    /* U+004B "K" */
    0x86, 0x29, 0x28, 0xc3, 0x0a, 0x24, 0x8a, 0x10,
    /* U+004C "L" */
    0x82, 0x08, 0x20, 0x82, 0x08, 0x20, 0x83, 0xf0,
    /* U+004D "M" */
    0x83, 0x8e, 0xac, 0x99, 0x30, 0x60, 0xc1, 0x83, 0x04,
    /* U+004E "N" */
    0x86, 0x18, 0x71, 0xa6, 0x58, 0xe1, 0x86, 0x10,
    /* U+004F "O" */
    0x7a, 0x18, 0x61, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+0050 "P" */
    0xfa, 0x18, 0x61, 0x87, 0xe8, 0x20, 0x82, 0x00,
    /* U+0051 "Q" */
    0x7a, 0x18, 0x61, 0x86, 0x18, 0x61, 0x95, 0xe0, 0x40,
    /* U+0052 "R" */
    0xfa, 0x18, 0x61, 0x87, 0xea, 0x24, 0x8a, 0x10,
    /* U+0053 "S" */
    0x7a, 0x18, 0x20, 0x78, 0x10, 0x61, 0x85, 0xe0,
    /* U+0054 "T" */
    0xfe, 0x20, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10, 0x20,
    /* U+0055 "U" */
    0x86, 0x18, 0x61, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+0056 "V" */
    0x86, 0x18, 0x61, 0x85, 0x24, 0x92, 0x30, 0xc0,
    /* U+0057 "W" */
    0x83, 0x06, 0x0c, 0x18, 0x32, 0x64, 0xd5, 0xc7, 0x04,
    /* U+0058 "X" */
    0x86, 0x14, 0x92, 0x30, 0xc4, 0x92, 0x86, 0x10,
    /* U+0059 "Y" */
    0x83, 0x05, 0x12, 0x22, 0x82, 0x04, 0x08, 0x10, 0x20,
    /* U+005A "Z" */
    0xfc, 0x10, 0x42, 0x10, 0x84, 0x20, 0x83, 0xf0,
    /* U+005B "[" */
    0xf2, 0x49, 0x24, 0x9c,
    /* U+005C "\\" */
    0x84, 0x10, 0x82, 0x10, 0x42, 0x08, 0x40,
    /* U+005D "]" */
    0xe4, 0x92, 0x49, 0x3c,
    /* U+005E "^" */
    0x22, 0xa2,
    /* U+005F "_" */
    0xfc,
    /* U+0060 "`" */
    0x90,
    /* U+0061 "a" */
    0x78, 0x17, 0xe1, 0x86, 0x17, 0xc0,
    /* U+0062 "b" */
    0x82, 0x08, 0x3e, 0x86, 0x18, 0x61, 0x87, 0xe0,
    /* U+0063 "c" */
    0x7a, 0x18, 0x20, 0x82, 0x17, 0x80,
    /* U+0064 "d" */
    0x04, 0x10, 0x5f, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+0065 "e" */
    0x7a, 0x18, 0x7f, 0x82, 0x07, 0x80,
    /* U+0066 "f" */
    0x1c, 0x82, 0x3e, 0x20, 0x82, 0x08, 0x20, 0x80,
    /* U+0067 "g" */
    0x7e, 0x18, 0x61, 0x86, 0x17, 0xc1, 0x05, 0xe0,
    /* U+0068 "h" */
    0x82, 0x08, 0x3e, 0x86, 0x18, 0x61, 0x86, 0x10,
    /* U+0069 "i" */
    0x48, 0x64, 0x92, 0x5c,
    /* U+006A "j" */
    0x08, 0x40, 0x30, 0x84, 0x21, 0x08, 0x63, 0x17, 0x00,
    /* U+006B "k" */
    0x82, 0x08, 0x21, 0x8a, 0x4e, 0x24, 0x8a, 0x10,
    /* U+006C "l" */
    0xc9, 0x24, 0x92, 0x5c,
    /* U+006D "m" */
    0xfd, 0x26, 0x4c, 0x99, 0x32, 0x64, 0x80,
    /* U+006E "n" */
    0xfa, 0x18, 0x61, 0x86, 0x18, 0x40,
    /* U+006F "o" */
    0x7a, 0x18, 0x61, 0x86, 0x17, 0x80,
    /* U+0070 "p" */
    0xfa, 0x18, 0x61, 0x86, 0x1f, 0xa0, 0x82, 0x00,
    /* U+0071 "q" */
    0x7e, 0x18, 0x61, 0x86, 0x17, 0xc1, 0x04, 0x10,
    /* U+0072 "r" */
    0xbf, 0x08, 0x20, 0x82, 0x08, 0x00,
    /* U+0073 "s" */
    0x7e, 0x08, 0x1e, 0x04, 0x1f, 0x80,
    /* U+0074 "t" */
    0x20, 0x82, 0x3e, 0x20, 0x82, 0x08, 0x20, 0x70,
    /* U+0075 "u" */
    0x86, 0x18, 0x61, 0x86, 0x17, 0xc0,
    /* U+0076 "v" */
    0x86, 0x18, 0x52, 0x48, 0xc3, 0x00,
    /* U+0077 "w" */
    0x83, 0x06, 0x4c, 0x99, 0x32, 0x5f, 0x00,
    /* U+0078 "x" */
    0x86, 0x14, 0x8c, 0x4a, 0x18, 0x40,
    /* U+0079 "y" */
    0x86, 0x18, 0x61, 0x86, 0x17, 0xc1, 0x05, 0xe0,
    /* U+007A "z" */
    0xfc, 0x21, 0x08, 0x42, 0x0f, 0xc0,
    /* U+007B "{" */
    0x34, 0x44, 0x84, 0x44, 0x43,
    /* U+007C "|" */
    0xff, 0xc0,
    /* U+007D "}" */
    0xc2, 0x22, 0x12, 0x22, 0x2c,
    /* U+007E "~" */
    0x63, 0x26, 0x30,
    /* U+00A0 " " */
    /* U+00A1 "¡" */
    0xdf, 0xc0,
    /* U+00A2 "¢" */
    0x10, 0x21, 0xf4, 0x99, 0x12, 0x24, 0x49, 0x7c, 0x20, 0x40,
    /* U+00A3 "£" */
    0x31, 0x24, 0x10, 0xf1, 0x04, 0x10, 0x47, 0xf0,
    /* U+00A4 "¤" */
    0x8b, 0xa3, 0x18, 0xba, 0x20,
    /* U+00A5 "¥" */
    0x83, 0x05, 0x11, 0x41, 0x0f, 0x84, 0x3e, 0x10, 0x20,
    /* U+00A6 "¦" */
    0xf3, 0xc0,
    /* U+00A7 "§" */
    0x74, 0x60, 0xc9, 0x46, 0x29, 0x30, 0x62, 0xe0,
    /* U+00A8 "¨" */
    0x99,
    /* U+00A9 "©" */
    0x7e, 0x81, 0x99, 0xa5, 0xa1, 0xa5, 0x99, 0x81, 0x7e,
    /* U+00AA "ª" */
    0x70, 0x5f, 0x17, 0x83, 0xe0,
    /* U+00AB "«" */
    0x12, 0x49, 0x24, 0x84, 0x84, 0x84, 0x80,
    /* U+00AC "¬" */
    0xfc, 0x10, 0x41,
    /* U+00AD "­" */
    0xf0,
    /* U+00AE "®" */
    0x7e, 0x81, 0xb9, 0xa5, 0xb9, 0xa9, 0xa5, 0x81, 0x7e,
    /* U+00AF "¯" */
    0xf0,
    /* U+00B0 "°" */
    0x69, 0x96,
    /* U+00B1 "±" */
    0x21, 0x3e, 0x42, 0x03, 0xe0,
    /* U+00B2 "²" */
    0x69, 0x12, 0x4f,
    /* U+00B3 "³" */
    0xe1, 0x61, 0x1e,
    /* U+00B4 "´" */
    0x60,
    /* U+00B5 "µ" */
    0x86, 0x18, 0x61, 0x86, 0x3f, 0x60, 0x82, 0x00,
    /* U+00B6 "¶" */
    0x7f, 0x26, 0x4c, 0x99, 0x2e, 0x44, 0x89, 0x12, 0x24,
    /* U+00B7 "·" */
    0xc0,
    /* U+00B8 "¸" */
    0x58,
    /* U+00B9 "¹" */
    0x59, 0x25, 0xc0,
    /* U+00BA "º" */
    0x74, 0x63, 0x17, 0x03, 0xe0,
    /* U+00BB "»" */
    0x90, 0x90, 0x90, 0x92, 0x49, 0x24, 0x00,
    /* U+00BC "¼" */
    0x20, 0xc0, 0x81, 0x12, 0x41, 0x04, 0x11, 0x47, 0x14, 0x78, 0x10, 0x20,
    /* U+00BD "½" */
    0x20, 0xc0, 0x81, 0x12, 0x41, 0x04, 0x10, 0x4d, 0x24, 0x10, 0x41, 0xe0,
    /* U+00BE "¾" */
    0xe0, 0x21, 0x80, 0x9e, 0x41, 0x04, 0x11, 0x47, 0x14, 0x78, 0x10, 0x20,
    /* U+00BF "¿" */
    0x20, 0x80, 0x08, 0x21, 0x08, 0x61, 0x85, 0xe0,
    /* U+00C0 "À" */
    0x20, 0x40, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C1 "Á" */
    0x10, 0x80, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C2 "Â" */
    0x31, 0x20, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C3 "Ã" */
    0x66, 0x60, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C4 "Ä" */
    0x49, 0x20, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C5 "Å" */
    0x31, 0x23, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+00C6 "Æ" */
    0x7f, 0x22, 0x44, 0x8f, 0xd2, 0x24, 0x48, 0x91, 0x3c,
    /* U+00C7 "Ç" */
    0x7a, 0x18, 0x60, 0x82, 0x08, 0x21, 0x85, 0xe2, 0x08, 0x40,
    /* U+00C8 "È" */
    0x20, 0x40, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+00C9 "É" */
    0x10, 0x80, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+00CA "Ê" */
    0x31, 0x20, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+00CB "Ë" */
    0x49, 0x20, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+00CC "Ì" */
    0x88, 0x74, 0x92, 0x49, 0x70,
    /* U+00CD "Í" */
    0x28, 0x74, 0x92, 0x49, 0x70,
    /* U+00CE "Î" */
    0x69, 0x0e, 0x44, 0x44, 0x44, 0x4e,
    /* U+00CF "Ï" */
    0x8c, 0x40, 0xe2, 0x10, 0x84, 0x21, 0x08, 0xe0,
    /* U+00D0 "Ð" */
    0x78, 0x89, 0x0a, 0x1f, 0x28, 0x50, 0xa1, 0x44, 0xf0,
    /* U+00D1 "Ñ" */
    0x66, 0x60, 0x21, 0x87, 0x1a, 0x65, 0x8e, 0x18, 0x61,
    /* U+00D2 "Ò" */
    0x20, 0x40, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00D3 "Ó" */
    0x10, 0x80, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00D4 "Ô" */
    0x31, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00D5 "Õ" */
    0x66, 0x60, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00D6 "Ö" */
    0x49, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00D7 "×" */
    0x85, 0x23, 0x0c, 0x4a, 0x10,
    /* U+00D8 "Ø" */
    0x3c, 0x43, 0x42, 0x46, 0x4a, 0x52, 0x62, 0x42, 0xc2, 0x3c,
    /* U+00D9 "Ù" */
    0x20, 0x48, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00DA "Ú" */
    0x10, 0x88, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00DB "Û" */
    0x31, 0x20, 0x21, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00DC "Ü" */
    0x49, 0x20, 0x21, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+00DD "Ý" */
    0x08, 0x22, 0x0c, 0x14, 0x48, 0x8a, 0x08, 0x10, 0x20, 0x40, 0x80,
    /* U+00DE "Þ" */
    0x82, 0x0f, 0xa1, 0x86, 0x18, 0x7e, 0x82, 0x00,
    /* U+00DF "ß" */
    0x72, 0x28, 0xa4, 0xfa, 0x18, 0x61, 0xc6, 0xe0,
    /* U+00E0 "à" */
    0x20, 0x40, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E1 "á" */
    0x10, 0x80, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E2 "â" */
    0x31, 0x20, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E3 "ã" */
    0x66, 0x60, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E4 "ä" */
    0x49, 0x20, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E5 "å" */
    0x31, 0x23, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+00E6 "æ" */
    0x6c, 0x25, 0xcc, 0xf9, 0x12, 0x1b, 0x00,
    /* U+00E7 "ç" */
    0x7a, 0x18, 0x20, 0x82, 0x17, 0x88, 0x21, 0x00,
    /* U+00E8 "è" */
    0x20, 0x40, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+00E9 "é" */
    0x10, 0x80, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+00EA "ê" */
    0x31, 0x20, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+00EB "ë" */
    0x49, 0x20, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+00EC "ì" */
    0x88, 0x64, 0x92, 0x5c,
    /* U+00ED "í" */
    0x28, 0x64, 0x92, 0x5c,
    /* U+00EE "î" */
    0x69, 0x06, 0x22, 0x22, 0x27,
    /* U+00EF "ï" */
    0x99, 0x06, 0x22, 0x22, 0x27,
    /* U+00F0 "ð" */
    0x50, 0x85, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F1 "ñ" */
    0x66, 0x60, 0x3e, 0x86, 0x18, 0x61, 0x86, 0x10,
    /* U+00F2 "ò" */
    0x20, 0x40, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F3 "ó" */
    0x10, 0x80, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F4 "ô" */
    0x31, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F5 "õ" */
    0x66, 0x60, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F6 "ö" */
    0x49, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+00F7 "÷" */
    0x21, 0x01, 0xf0, 0x10, 0x80,
    /* U+00F8 "ø" */
    0x02, 0x79, 0x1a, 0x55, 0x2c, 0x50, 0xde,
    /* U+00F9 "ù" */
    0x20, 0x40, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+00FA "ú" */
    0x10, 0x80, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+00FB "û" */
    0x31, 0x20, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+00FC "ü" */
    0x49, 0x20, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+00FD "ý" */
    0x10, 0x80, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+00FE "þ" */
    0x82, 0x08, 0x3e, 0x86, 0x18, 0x61, 0x87, 0xe8, 0x20, 0x80,
    /* U+00FF "ÿ" */
    0x49, 0x20, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+0100 "Ā" */
    0x78, 0x07, 0xa1, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+0101 "ā" */
    0x78, 0x07, 0x81, 0x7e, 0x18, 0x61, 0x7c,
    /* U+0102 "Ă" */
    0x48, 0xc0, 0x1e, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+0103 "ă" */
    0x48, 0xc0, 0x1e, 0x05, 0xf8, 0x61, 0x85, 0xf0,
    /* U+0104 "Ą" */
    0x79, 0x0a, 0x14, 0x28, 0x5f, 0xa1, 0x42, 0x85, 0x08, 0x10, 0x40, 0x60,
    /* U+0105 "ą" */
    0x78, 0x09, 0xf4, 0x28, 0x50, 0x9f, 0x02, 0x08, 0x0c,
    /* U+0106 "Ć" */
    0x10, 0x80, 0x1e, 0x86, 0x18, 0x20, 0x82, 0x18, 0x5e,
    /* U+0107 "ć" */
    0x10, 0x80, 0x1e, 0x86, 0x08, 0x20, 0x85, 0xe0,
    /* U+0108 "Ĉ" */
    0x31, 0x20, 0x1e, 0x86, 0x18, 0x20, 0x82, 0x18, 0x5e,
    /* U+0109 "ĉ" */
    0x31, 0x20, 0x1e, 0x86, 0x08, 0x20, 0x85, 0xe0,
    /* U+010A "Ċ" */
    0x20, 0x80, 0x1e, 0x86, 0x18, 0x20, 0x82, 0x18, 0x5e,
    /* U+010B "ċ" */
    0x20, 0x80, 0x1e, 0x86, 0x08, 0x20, 0x85, 0xe0,
    /* U+010C "Č" */
    0x48, 0xc0, 0x1e, 0x86, 0x18, 0x20, 0x82, 0x18, 0x5e,
    /* U+010D "č" */
    0x48, 0xc0, 0x1e, 0x86, 0x08, 0x20, 0x85, 0xe0,
    /* U+010E "Ď" */
    0x48, 0xc0, 0x3c, 0x8a, 0x18, 0x61, 0x86, 0x18, 0xbc,
    /* U+010F "ď" */
    0x48, 0xc0, 0x41, 0x05, 0xf8, 0x61, 0x86, 0x18, 0x5f,
    /* U+0110 "Đ" */
    0x78, 0x89, 0x0a, 0x1f, 0x28, 0x50, 0xa1, 0x44, 0xf0,
    /* U+0111 "đ" */
    0x04, 0x3c, 0x13, 0xe8, 0x50, 0xa1, 0x42, 0x84, 0xf8,
    /* U+0112 "Ē" */
    0x78, 0x0f, 0xe0, 0x82, 0x0f, 0x20, 0x82, 0x08, 0x3f,
    /* U+0113 "ē" */
    0x78, 0x07, 0xa1, 0x87, 0xf8, 0x20, 0x78,
    /* U+0114 "Ĕ" */
    0x48, 0xc0, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+0115 "ĕ" */
    0x48, 0xc0, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+0116 "Ė" */
    0x20, 0x80, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+0117 "ė" */
    0x20, 0x80, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+0118 "Ę" */
    0xfd, 0x02, 0x04, 0x0f, 0x10, 0x20, 0x40, 0x81, 0xf8, 0x10, 0x40, 0x60,
    /* U+0119 "ę" */
    0x7a, 0x18, 0x7f, 0x82, 0x07, 0x84, 0x20, 0x60,
    /* U+011A "Ě" */
    0x48, 0xc0, 0x3f, 0x82, 0x08, 0x3c, 0x82, 0x08, 0x3f,
    /* U+011B "ě" */
    0x48, 0xc0, 0x1e, 0x86, 0x1f, 0xe0, 0x81, 0xe0,
    /* U+011C "Ĝ" */
    0x31, 0x20, 0x1e, 0x86, 0x08, 0x27, 0x86, 0x18, 0x5e,
    /* U+011D "ĝ" */
    0x31, 0x20, 0x1f, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+011E "Ğ" */
    0x48, 0xc0, 0x1e, 0x86, 0x08, 0x27, 0x86, 0x18, 0x5e,
    /* U+011F "ğ" */
    0x48, 0xc0, 0x1f, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+0120 "Ġ" */
    0x20, 0x80, 0x1e, 0x86, 0x08, 0x27, 0x86, 0x18, 0x5e,
    /* U+0121 "ġ" */
    0x10, 0x40, 0x1f, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+0122 "Ģ" */
    0x7a, 0x18, 0x60, 0x82, 0x78, 0x61, 0x85, 0xe0, 0x08, 0x21, 0x00,
    /* U+0123 "ģ" */
    0x08, 0x41, 0x00, 0x7e, 0x18, 0x61, 0x86, 0x17, 0xc1, 0x05, 0xe0,
    /* U+0124 "Ĥ" */
    0x31, 0x20, 0x21, 0x86, 0x18, 0x7f, 0x86, 0x18, 0x61,
    /* U+0125 "ĥ" */
    0x18, 0x98, 0x20, 0x83, 0xe8, 0x61, 0x86, 0x18, 0x61,
    /* U+0126 "Ħ" */
    0x42, 0xff, 0x42, 0x42, 0x7e, 0x42, 0x42, 0x42, 0x42, 0x42,
    /* U+0127 "ħ" */
    0x41, 0xe1, 0x03, 0xe4, 0x28, 0x50, 0xa1, 0x42, 0x84,
    /* U+0128 "Ĩ" */
    0x66, 0x60, 0x1c, 0x20, 0x82, 0x08, 0x20, 0x82, 0x1c,
    /* U+0129 "ĩ" */
    0x6d, 0x80, 0xc2, 0x10, 0x84, 0x23, 0x80,
    /* U+012A "Ī" */
    0xf8, 0x1c, 0x42, 0x10, 0x84, 0x21, 0x08, 0xe0,
    /* U+012B "ī" */
    0xf0, 0x62, 0x22, 0x22, 0x70,
    /* U+012C "Ĭ" */
    0x96, 0x0e, 0x44, 0x44, 0x44, 0x4e,
    /* U+012D "ĭ" */
    0x96, 0x06, 0x22, 0x22, 0x27,
    /* U+012E "Į" */
    0xe9, 0x24, 0x92, 0x5d, 0x46,
    /* U+012F "į" */
    0x48, 0x64, 0x92, 0x5d, 0x46,
    /* U+0130 "İ" */
    0x48, 0x74, 0x92, 0x49, 0x70,
    /* U+0131 "ı" */
    0xc9, 0x24, 0xb8,
    /* U+0132 "Ĳ" */
    0xe7, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x52, 0x52, 0xec,
    /* U+0133 "ĳ" */
    0x42, 0x84, 0x06, 0x34, 0x28, 0x50, 0xa1, 0x43, 0xc4, 0x48, 0x90, 0xc0,
    /* U+0134 "Ĵ" */
    0x18, 0x90, 0x07, 0x08, 0x20, 0x82, 0x0a, 0x28, 0x9c,
    /* U+0135 "ĵ" */
    0x18, 0x90, 0x06, 0x08, 0x20, 0x82, 0x08, 0x28, 0xa2, 0x70,
    /* U+0136 "Ķ" */
    0x86, 0x29, 0x28, 0xc3, 0x0a, 0x24, 0x8a, 0x10, 0x08, 0x21, 0x00,
    /* U+0137 "ķ" */
    0x82, 0x08, 0x21, 0x8a, 0x4e, 0x24, 0x8a, 0x10, 0x08, 0x21, 0x00,
    /* U+0138 "ĸ" */
    0x86, 0x29, 0x38, 0x92, 0x28, 0x40,
    /* U+0139 "Ĺ" */
    0x42, 0x00, 0x20, 0x82, 0x08, 0x20, 0x82, 0x08, 0x3f,
    /* U+013A "ĺ" */
    0x28, 0x64, 0x92, 0x49, 0x70,
    /* U+013B "Ļ" */
    0x82, 0x08, 0x20, 0x82, 0x08, 0x20, 0x83, 0xf0, 0x08, 0x21, 0x00,
    /* U+013C "ļ" */
    0xc9, 0x24, 0x92, 0x5c, 0x25, 0x00,
    /* U+013D "Ľ" */
    0x48, 0xc8, 0x20, 0x82, 0x08, 0x20, 0x82, 0x08, 0x3f,
    /* U+013E "ľ" */
    0x96, 0x06, 0x22, 0x22, 0x22, 0x27,
    /* U+013F "Ŀ" */
    0x82, 0x08, 0x20, 0x8a, 0x28, 0x20, 0x83, 0xf0,
    /* U+0140 "ŀ" */
    0xc1, 0x04, 0x10, 0x45, 0x14, 0x10, 0x43, 0x80,
    /* U+0141 "Ł" */
    0x40, 0x81, 0x02, 0x06, 0x18, 0x10, 0x20, 0x40, 0xfc,
    /* U+0142 "ł" */
    0xc9, 0x27, 0x92, 0x5c,
    /* U+0143 "Ń" */
    0x10, 0x88, 0x61, 0x87, 0x1a, 0x65, 0x8e, 0x18, 0x61,
    /* U+0144 "ń" */
    0x10, 0x80, 0x3e, 0x86, 0x18, 0x61, 0x86, 0x10,
    /* U+0145 "Ņ" */
    0x86, 0x18, 0x71, 0xa6, 0x58, 0xe1, 0x86, 0x10, 0x08, 0x21, 0x00,
    /* U+0146 "ņ" */
    0xfa, 0x18, 0x61, 0x86, 0x18, 0x40, 0x20, 0x84, 0x00,
    /* U+0147 "Ň" */
    0x48, 0xc8, 0x61, 0x87, 0x1a, 0x65, 0x8e, 0x18, 0x61,
    /* U+0148 "ň" */
    0x48, 0xc0, 0x3e, 0x86, 0x18, 0x61, 0x86, 0x10,
    /* U+0149 "ŉ" */
    0x40, 0x82, 0x00, 0x07, 0xc8, 0x50, 0xa1, 0x42, 0x85, 0x08,
    /* U+014A "Ŋ" */
    0x86, 0x18, 0x71, 0xa6, 0x58, 0xe1, 0x86, 0x10, 0x41, 0x18,
    /* U+014B "ŋ" */
    0xfa, 0x18, 0x61, 0x86, 0x18, 0x41, 0x04, 0x60,
    /* U+014C "Ō" */
    0x78, 0x07, 0xa1, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+014D "ō" */
    0x78, 0x07, 0xa1, 0x86, 0x18, 0x61, 0x78,
    /* U+014E "Ŏ" */
    0x48, 0xc0, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+014F "ŏ" */
    0x48, 0xc0, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+0150 "Ő" */
    0x25, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+0151 "ő" */
    0x25, 0x20, 0x1e, 0x86, 0x18, 0x61, 0x85, 0xe0,
    /* U+0152 "Œ" */
    0x7f, 0x22, 0x44, 0x89, 0xd2, 0x24, 0x48, 0x90, 0xfc,
    /* U+0153 "œ" */
    0x7d, 0x26, 0x4c, 0xf9, 0x12, 0x1f, 0x00,
    /* U+0154 "Ŕ" */
    0x10, 0x80, 0x3e, 0x86, 0x18, 0x7e, 0xa2, 0x48, 0xa1,
    /* U+0155 "ŕ" */
    0x10, 0x80, 0x2f, 0xc2, 0x08, 0x20, 0x82, 0x00,
    /* U+0156 "Ŗ" */
    0xfa, 0x18, 0x61, 0x87, 0xea, 0x24, 0x8a, 0x10, 0x08, 0x21, 0x00,
    /* U+0157 "ŗ" */
    0x5e, 0xc1, 0x02, 0x04, 0x08, 0x10, 0x00, 0x40, 0x82, 0x00,
    /* U+0158 "Ř" */
    0x48, 0xc0, 0x3e, 0x86, 0x18, 0x7e, 0xa2, 0x48, 0xa1,
    /* U+0159 "ř" */
    0x48, 0xc0, 0x2f, 0xc2, 0x08, 0x20, 0x82, 0x00,
    /* U+015A "Ś" */
    0x10, 0x80, 0x1e, 0x86, 0x08, 0x1e, 0x04, 0x18, 0x5e,
    /* U+015B "ś" */
    0x08, 0x40, 0x1f, 0x82, 0x07, 0x81, 0x07, 0xe0,
    /* U+015C "Ŝ" */
    0x31, 0x20, 0x1e, 0x86, 0x08, 0x1e, 0x04, 0x18, 0x5e,
    /* U+015D "ŝ" */
    0x31, 0x20, 0x1f, 0x82, 0x07, 0x81, 0x07, 0xe0,
    /* U+015E "Ş" */
    0x7a, 0x18, 0x20, 0x78, 0x10, 0x61, 0x85, 0xe2, 0x08, 0x40,
    /* U+015F "ş" */
    0x7e, 0x08, 0x1e, 0x04, 0x1f, 0x88, 0x21, 0x00,
    /* U+0160 "Š" */
    0x48, 0xc0, 0x1e, 0x86, 0x08, 0x1e, 0x04, 0x18, 0x5e,
    /* U+0161 "š" */
    0x48, 0xc0, 0x1f, 0x82, 0x07, 0x81, 0x07, 0xe0,
    /* U+0162 "Ţ" */
    0xfe, 0x20, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10, 0x20, 0x20, 0x41, 0x00,
    /* U+0163 "ţ" */
    0x20, 0x82, 0x3e, 0x20, 0x82, 0x08, 0x20, 0x70, 0x82, 0x10,
    /* U+0164 "Ť" */
    0x24, 0x30, 0x07, 0xf1, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,
    /* U+0165 "ť" */
    0x48, 0xc0, 0x08, 0x23, 0xe2, 0x08, 0x20, 0x82, 0x07,
    /* U+0166 "Ŧ" */
    0xfe, 0x20, 0x40, 0x87, 0xc2, 0x04, 0x08, 0x10, 0x20,
    /* U+0167 "ŧ" */
    0x20, 0x82, 0x3e, 0x21, 0xc2, 0x08, 0x20, 0x70,
    /* U+0168 "Ũ" */
    0x66, 0x60, 0x21, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+0169 "ũ" */
    0x66, 0x60, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+016A "Ū" */
    0x78, 0x08, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+016B "ū" */
    0x78, 0x08, 0x61, 0x86, 0x18, 0x61, 0x7c,
    /* U+016C "Ŭ" */
    0x48, 0xc8, 0x61, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+016D "ŭ" */
    0x48, 0xc0, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+016E "Ů" */
    0x31, 0x23, 0x21, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+016F "ů" */
    0x31, 0x23, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+0170 "Ű" */
    0x25, 0x20, 0x21, 0x86, 0x18, 0x61, 0x86, 0x18, 0x5e,
    /* U+0171 "ű" */
    0x25, 0x20, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0,
    /* U+0172 "Ų" */
    0x86, 0x18, 0x61, 0x86, 0x18, 0x61, 0x85, 0xe1, 0x08, 0x18,
    /* U+0173 "ų" */
    0x85, 0x0a, 0x14, 0x28, 0x50, 0x9f, 0x02, 0x08, 0x0c,
    /* U+0174 "Ŵ" */
    0x18, 0x48, 0x04, 0x18, 0x30, 0x60, 0xc9, 0x93, 0x57, 0x1c, 0x10,
    /* U+0175 "ŵ" */
    0x18, 0x48, 0x04, 0x18, 0x32, 0x64, 0xc9, 0x92, 0xf8,
    /* U+0176 "Ŷ" */
    0x18, 0x48, 0x04, 0x18, 0x28, 0x91, 0x14, 0x10, 0x20, 0x40, 0x80,
    /* U+0177 "ŷ" */
    0x31, 0x20, 0x21, 0x86, 0x18, 0x61, 0x85, 0xf0, 0x41, 0x78,
    /* U+0178 "Ÿ" */
    0x44, 0x88, 0x04, 0x18, 0x28, 0x91, 0x14, 0x10, 0x20, 0x40, 0x80,
    /* U+0179 "Ź" */
    0x10, 0x80, 0x3f, 0x04, 0x21, 0x08, 0x42, 0x08, 0x3f,
    /* U+017A "ź" */
    0x10, 0x80, 0x3f, 0x08, 0x42, 0x10, 0x83, 0xf0,
    /* U+017B "Ż" */
    0x20, 0x80, 0x3f, 0x04, 0x21, 0x08, 0x42, 0x08, 0x3f,
    /* U+017C "ż" */
    0x20, 0x80, 0x3f, 0x08, 0x42, 0x10, 0x83, 0xf0,
    /* U+017D "Ž" */
    0x48, 0xc0, 0x3f, 0x04, 0x21, 0x08, 0x42, 0x08, 0x3f,
    /* U+017E "ž" */
    0x48, 0xc0, 0x3f, 0x08, 0x42, 0x10, 0x83, 0xf0,
    /* U+017F "ſ" */
    0x78, 0x88, 0x88, 0x88, 0x88,
    /* U+0218 "Ș" */
    0x7a, 0x18, 0x20, 0x78, 0x10, 0x61, 0x85, 0xe0, 0x08, 0x21, 0x00,
    /* U+0219 "ș" */
    0x7e, 0x08, 0x1e, 0x04, 0x1f, 0x80, 0x20, 0x84, 0x00,
    /* U+021A "Ț" */
    0xfe, 0x20, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10, 0x20, 0x00, 0x81, 0x04,
    0x00,
    /* U+021B "ț" */
    0x20, 0x82, 0x3e, 0x20, 0x82, 0x08, 0x20, 0x70, 0x02, 0x08, 0x40,
    /* U+2022 "•" */
    0x6f, 0xf6,
    /* U+20AC "€" */
    0x1c, 0x45, 0x07, 0xc4, 0x1f, 0x10, 0x11, 0x1c,
    0x00 /* keeps the array non-empty */
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 128, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 128, .box_w = 1, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 2, .adv_w = 128, .box_w = 4, .box_h = 3, .ofs_x = 2, .ofs_y = 8},
    {.bitmap_index = 4, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 12, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 24, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 33, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 41, .adv_w = 128, .box_w = 1, .box_h = 3, .ofs_x = 3, .ofs_y = 8},
    {.bitmap_index = 42, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 46, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 50, .adv_w = 128, .box_w = 6, .box_h = 5, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 54, .adv_w = 128, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 58, .adv_w = 128, .box_w = 2, .box_h = 3, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 59, .adv_w = 128, .box_w = 6, .box_h = 1, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 60, .adv_w = 128, .box_w = 1, .box_h = 2, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 61, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 68, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 76, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 83, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 91, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 99, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 107, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 115, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 123, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 131, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 139, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 147, .adv_w = 128, .box_w = 1, .box_h = 7, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 148, .adv_w = 128, .box_w = 2, .box_h = 8, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 150, .adv_w = 128, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 156, .adv_w = 128, .box_w = 6, .box_h = 4, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 159, .adv_w = 128, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 165, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 173, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 182, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 190, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 198, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 206, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 214, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 222, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 230, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 238, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 246, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 250, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 258, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 266, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 274, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 283, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 291, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 299, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 307, .adv_w = 128, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 316, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 324, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 332, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 341, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 349, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 357, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 366, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 374, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 383, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 391, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 395, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 402, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 406, .adv_w = 128, .box_w = 5, .box_h = 3, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 408, .adv_w = 128, .box_w = 6, .box_h = 1, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 409, .adv_w = 128, .box_w = 2, .box_h = 2, .ofs_x = 3, .ofs_y = 10},
    {.bitmap_index = 410, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 416, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 424, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 430, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 438, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 444, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 452, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 460, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 468, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 472, .adv_w = 128, .box_w = 5, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 481, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 489, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 493, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 500, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 506, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 512, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 520, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 528, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 534, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 540, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 548, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 554, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 560, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 567, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 573, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 581, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 587, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 592, .adv_w = 128, .box_w = 1, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 594, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 599, .adv_w = 128, .box_w = 7, .box_h = 3, .ofs_x = 0, .ofs_y = 8},
    {.bitmap_index = 602, .adv_w = 128, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 602, .adv_w = 128, .box_w = 1, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 604, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 614, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 622, .adv_w = 128, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 627, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 636, .adv_w = 128, .box_w = 1, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 638, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 646, .adv_w = 128, .box_w = 4, .box_h = 2, .ofs_x = 2, .ofs_y = 10},
    {.bitmap_index = 647, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 656, .adv_w = 128, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 661, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 668, .adv_w = 128, .box_w = 6, .box_h = 4, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 671, .adv_w = 128, .box_w = 4, .box_h = 1, .ofs_x = 2, .ofs_y = 4},
    {.bitmap_index = 672, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 681, .adv_w = 128, .box_w = 4, .box_h = 1, .ofs_x = 2, .ofs_y = 11},
    {.bitmap_index = 682, .adv_w = 128, .box_w = 4, .box_h = 4, .ofs_x = 2, .ofs_y = 7},
    {.bitmap_index = 684, .adv_w = 128, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 689, .adv_w = 128, .box_w = 4, .box_h = 6, .ofs_x = 2, .ofs_y = 5},
    {.bitmap_index = 692, .adv_w = 128, .box_w = 4, .box_h = 6, .ofs_x = 2, .ofs_y = 5},
    {.bitmap_index = 695, .adv_w = 128, .box_w = 2, .box_h = 2, .ofs_x = 3, .ofs_y = 10},
    {.bitmap_index = 696, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 704, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 713, .adv_w = 128, .box_w = 1, .box_h = 2, .ofs_x = 3, .ofs_y = 3},
    {.bitmap_index = 714, .adv_w = 128, .box_w = 2, .box_h = 3, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 715, .adv_w = 128, .box_w = 3, .box_h = 6, .ofs_x = 2, .ofs_y = 5},
    {.bitmap_index = 718, .adv_w = 128, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 723, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 730, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 742, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 754, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 766, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 774, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 783, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 792, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 801, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 810, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 819, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 828, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 837, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 847, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 856, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 865, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 874, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 883, .adv_w = 128, .box_w = 3, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 888, .adv_w = 128, .box_w = 3, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 893, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 899, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 907, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 916, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 925, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 934, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 943, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 952, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 961, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 970, .adv_w = 128, .box_w = 6, .box_h = 6, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 975, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 985, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 994, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1003, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1012, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1021, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1032, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1040, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1048, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1056, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1064, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1072, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1080, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1088, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1096, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1103, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1111, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1119, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1127, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1135, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1143, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1147, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1151, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1156, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1161, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1169, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1177, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1185, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1193, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1201, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1209, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1217, .adv_w = 128, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 1222, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1229, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1237, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1245, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1253, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1261, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1271, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1281, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1291, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1300, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1307, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1316, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1324, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1336, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1345, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1354, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1362, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1371, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1379, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1388, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1396, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1405, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1413, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1422, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1431, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1440, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1449, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1458, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1465, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1474, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1482, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1491, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1499, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1511, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1519, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1528, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1536, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1545, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1555, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1564, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1574, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1583, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1593, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1604, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1615, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1624, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1633, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1643, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1652, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1661, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1668, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1676, .adv_w = 128, .box_w = 4, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1681, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1687, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1692, .adv_w = 128, .box_w = 3, .box_h = 13, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 1697, .adv_w = 128, .box_w = 3, .box_h = 13, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 1702, .adv_w = 128, .box_w = 3, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1707, .adv_w = 128, .box_w = 3, .box_h = 7, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1710, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1720, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 1732, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1741, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1751, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1762, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1773, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1779, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1788, .adv_w = 128, .box_w = 3, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1793, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1804, .adv_w = 128, .box_w = 3, .box_h = 14, .ofs_x = 2, .ofs_y = -4},
    {.bitmap_index = 1810, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1819, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1825, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1833, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1841, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1850, .adv_w = 128, .box_w = 3, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1854, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1863, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1871, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1882, .adv_w = 128, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 1891, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1900, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1908, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1918, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1928, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 1936, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1945, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1952, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1961, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1969, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1978, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1986, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1995, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2002, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2011, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2019, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 2030, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = -4},
    {.bitmap_index = 2040, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2049, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2057, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2066, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2074, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2083, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2091, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2101, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2109, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2118, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2126, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 2138, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2148, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2159, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2168, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2177, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2185, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2194, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2202, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2211, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2218, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2227, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2235, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2244, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2252, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2261, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2269, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2279, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2288, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2299, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2308, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2319, .adv_w = 128, .box_w = 6, .box_h = 13, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 2329, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2340, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2349, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2357, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2366, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2374, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2383, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2391, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 2396, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 2407, .adv_w = 128, .box_w = 6, .box_h = 11, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 2416, .adv_w = 128, .box_w = 7, .box_h = 14, .ofs_x = 0, .ofs_y = -4},
    {.bitmap_index = 2429, .adv_w = 128, .box_w = 6, .box_h = 14, .ofs_x = 1, .ofs_y = -4},
    {.bitmap_index = 2440, .adv_w = 128, .box_w = 4, .box_h = 4, .ofs_x = 2, .ofs_y = 2},
    {.bitmap_index = 2442, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 32, .range_length = 95, .glyph_id_start = 1,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 160, .range_length = 224, .glyph_id_start = 96,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 536, .range_length = 4, .glyph_id_start = 320,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8226, .range_length = 1, .glyph_id_start = 324,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8364, .range_length = 1, .glyph_id_start = 325,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 5,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t lv_font_montserrat_16 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 18,
    .base_line = 5,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_eink_symbols_16,
    .user_data = NULL,
};
