/* Generated by tools/gen_eink_fonts.py -- do not edit.
 * LVGL's LV_SYMBOL_* icons (Font Awesome 5 Free, SIL OFL 1.1) at 8 px,
 * 1 bpp: the fallback of the T-Deck Pro's Terminus faces. */

/*******************************************************************************
 * Size: 8 px
 * Bpp: 1
 * Opts: --no-compress --no-prefilter --bpp 1 --size 8 --font FontAwesome5-Solid+Brands+Regular.woff -r 61441,61448,61451,61452,61452,61453,61457,61459,61461,61465,61468,61473,61478,61479,61480,61502,61507,61512,61515,61516,61517,61521,61522,61523,61524,61543,61544,61550,61552,61553,61556,61559,61560,61561,61563,61587,61589,61636,61637,61639,61641,61664,61671,61674,61683,61724,61732,61787,61931,62016,62017,62018,62019,62020,62087,62099,62212,62189,62810,63426,63650 --format lvgl -o src/fonts/eink/lv_font_eink_symbols_8.c --force-fast-kern-format
 ******************************************************************************/

#include <lvgl.h>

#ifndef LV_FONT_EINK_SYMBOLS_8
#define LV_FONT_EINK_SYMBOLS_8 1
#endif

#if LV_FONT_EINK_SYMBOLS_8

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+F001 "" */
    0x3, 0x3f, 0x3d, 0x21, 0x21, 0x27, 0xe7, 0xe0,

    /* U+F008 "" */
    0xff, 0xd1, 0x78, 0xff, 0xfa, 0x2f, 0xfc,

    /* U+F00B "" */
    0xde, 0xff, 0xde, 0xff, 0xff, 0x0, 0xff, 0xff,

    /* U+F00C "" */
    0x3, 0x7, 0xce, 0xfc, 0x78, 0x30,

    /* U+F00D "" */
    0xcd, 0xe3, 0x1e, 0xcc,

    /* U+F011 "" */
    0x10, 0xab, 0x5c, 0x98, 0x30, 0x51, 0x1c,

    /* U+F013 "" */
    0x18, 0x5c, 0xff, 0x66, 0x66, 0xff, 0x7c, 0x18,

    /* U+F015 "" */
    0xb, 0x1b, 0x9a, 0xdf, 0xf7, 0xf3, 0xb9, 0xdc,

    /* U+F019 "" */
    0x18, 0xc, 0x6, 0xf, 0xc3, 0xc7, 0xfb, 0xfb,
    0xff,

    /* U+F01C "" */
    0x3e, 0x20, 0xb0, 0x7c, 0x7f, 0xff, 0xfc,

    /* U+F021 "" */
    0x3d, 0x43, 0xc7, 0x0, 0x0, 0xe3, 0xc6, 0xbc,

    /* U+F026 "" */
    0x3, 0xff, 0xf3, 0x0,

    /* U+F027 "" */
    0x0, 0xcf, 0x7d, 0xf0, 0xc0, 0x0,

    /* U+F028 "" */
    0x2, 0x0, 0x8c, 0xbe, 0xdf, 0x6f, 0x94, 0xc4,
    0x4,

    /* U+F03E "" */
    0xff, 0x9f, 0xfb, 0xd1, 0x81, 0xff,

    /* U+F043 "" */
    0x20, 0xc7, 0x1e, 0xfa, 0xed, 0x9c,

    /* U+F048 "" */
    0x8c, 0xff, 0xff, 0xce, 0x20,

    /* U+F04B "" */
    0xc1, 0xe3, 0xe7, 0xff, 0xff, 0x38, 0x60,

    /* U+F04C "" */
    0xef, 0xdf, 0xbf, 0x7e, 0xfd, 0xfb, 0x80,

    /* U+F04D "" */
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x80,

    /* U+F051 "" */
    0x8e, 0x7f, 0xff, 0xe6, 0x20,

    /* U+F052 "" */
    0x10, 0x71, 0xf7, 0xf0, 0x1f, 0xff, 0x80,

    /* U+F053 "" */
    0x11, 0x99, 0x86, 0x18, 0x40,

    /* U+F054 "" */
    0x43, 0xc, 0x33, 0x31, 0x0,

    /* U+F067 "" */
    0x10, 0x20, 0x47, 0xf1, 0x2, 0x4, 0x0,

    /* U+F068 "" */
    0xfe,

    /* U+F06E "" */
    0x3e, 0x31, 0xb7, 0x7b, 0xb6, 0x31, 0xf0,

    /* U+F070 "" */
    0x40, 0xd, 0xe0, 0x76, 0x37, 0x66, 0x6c, 0x63,
    0x7, 0x30, 0x2,

    /* U+F071 "" */
    0x8, 0xe, 0x7, 0x6, 0xc7, 0x73, 0xfb, 0xdf,
    0xff,

    /* U+F074 "" */
    0x2, 0xef, 0x3a, 0x3a, 0xef, 0x2,

    /* U+F077 "" */
    0x10, 0x71, 0xb6, 0x30,

    /* U+F078 "" */
    0x82, 0xd8, 0xe0, 0x80,

    /* U+F079 "" */
    0x40, 0x77, 0xb8, 0x48, 0x24, 0x3b, 0xdc, 0x4,

    /* U+F07B "" */
    0xf0, 0xff, 0xff, 0xff, 0xff, 0xff,

    /* U+F093 "" */
    0x8, 0xe, 0xf, 0x83, 0x81, 0xc7, 0xfb, 0xfb,
    0xff,

    /* U+F095 "" */
    0x3, 0x7, 0x7, 0x2, 0x6, 0x6c, 0xf8, 0xe0,

    /* U+F0C4 "" */
    0xe7, 0x5b, 0xe1, 0x8f, 0x95, 0xb9, 0x80,

    /* U+F0C5 "" */
    0x3d, 0xf3, 0xff, 0xff, 0xff, 0xf7, 0xfc,

    /* U+F0C7 "" */
    0xfd, 0xe, 0x1f, 0xfe, 0xfd, 0xff, 0x80,

    /* U+F0C9 "" */
    0xff, 0xfc, 0x7, 0xf0, 0x0, 0x3f, 0x80,

    /* U+F0E0 "" */
    0xff, 0xff, 0xbc, 0xdb, 0xe7, 0xff,

    /* U+F0E7 "" */
    0xe7, 0x3f, 0xf3, 0x10, 0x80,

    /* U+F0EA "" */
    0xf9, 0xf3, 0x7, 0xef, 0x9f, 0xff, 0x9f,

    /* U+F0F3 "" */
    0x10, 0x71, 0xf3, 0xe7, 0xdf, 0xff, 0x88,

    /* U+F11C "" */
    0xff, 0xdd, 0x7b, 0x7f, 0xfa, 0x2f, 0xfc,

    /* U+F124 "" */
    0x3, 0xf, 0x3e, 0xfe, 0x7c, 0x1c, 0x18, 0x8,

    /* U+F15B "" */
    0xf9, 0xfb, 0xc7, 0xff, 0xff, 0xff, 0xff,

    /* U+F1EB "" */
    0x0, 0x1f, 0xec, 0xc, 0x78, 0x21, 0x0, 0x0,
    0xc0, 0x30,

    /* U+F240 "" */
    0xff, 0xa0, 0x3f, 0xf7, 0xff, 0xff, 0xc0,

    /* U+F241 "" */
    0xff, 0xa0, 0x3f, 0xe7, 0xfb, 0xff, 0xc0,

    /* U+F242 "" */
    0xff, 0xa0, 0x3f, 0x87, 0xe3, 0xff, 0xc0,

    /* U+F243 "" */
    0xff, 0xa0, 0x3f, 0x7, 0xc3, 0xff, 0xc0,

    /* U+F244 "" */
    0xff, 0xa0, 0x38, 0x6, 0x3, 0xff, 0x80,

    /* U+F287 "" */
    0xe, 0x4, 0xd, 0xb, 0xff, 0xc8, 0x81, 0xc0,

    /* U+F293 "" */
    0x7b, 0xbb, 0x73, 0xce, 0xde, 0xde,

    /* U+F2ED "" */
    0xff, 0xff, 0xff, 0x7e, 0xfd, 0xfb, 0xbe,

    /* U+F304 "" */
    0x6, 0xf, 0x1f, 0x3e, 0x7c, 0xf8, 0xf0, 0xe0,

    /* U+F55A "" */
    0x3f, 0xdf, 0xff, 0x9f, 0xe7, 0x7f, 0xcf, 0xf0,

    /* U+F7C2 "" */
    0x3e, 0xd7, 0xaf, 0xff, 0xff, 0xff, 0xff,

    /* U+F8A2 "" */
    0x1, 0x61, 0xff, 0x60
};


/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 8, .adv_w = 128, .box_w = 9, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 15, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 23, .adv_w = 128, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 29, .adv_w = 88, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 33, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 40, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 48, .adv_w = 144, .box_w = 9, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 56, .adv_w = 128, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 65, .adv_w = 144, .box_w = 9, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 72, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 80, .adv_w = 64, .box_w = 4, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 84, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 90, .adv_w = 144, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 99, .adv_w = 128, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 105, .adv_w = 88, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 111, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 116, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 123, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 130, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 137, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 142, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 149, .adv_w = 80, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 154, .adv_w = 80, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 159, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 166, .adv_w = 112, .box_w = 7, .box_h = 1, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 167, .adv_w = 144, .box_w = 9, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 174, .adv_w = 160, .box_w = 11, .box_h = 8, .ofs_x = -1, .ofs_y = -1},
    {.bitmap_index = 185, .adv_w = 144, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 194, .adv_w = 128, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 200, .adv_w = 112, .box_w = 7, .box_h = 4, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 204, .adv_w = 112, .box_w = 7, .box_h = 4, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 208, .adv_w = 160, .box_w = 9, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 216, .adv_w = 128, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 222, .adv_w = 128, .box_w = 9, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 231, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 239, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 246, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 253, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 260, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 267, .adv_w = 128, .box_w = 8, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 273, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 278, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 285, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 292, .adv_w = 144, .box_w = 9, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 299, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 307, .adv_w = 96, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 314, .adv_w = 160, .box_w = 10, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 324, .adv_w = 160, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 331, .adv_w = 160, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 338, .adv_w = 160, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 345, .adv_w = 160, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 352, .adv_w = 160, .box_w = 10, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 359, .adv_w = 160, .box_w = 10, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 367, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 373, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 380, .adv_w = 128, .box_w = 8, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 388, .adv_w = 160, .box_w = 10, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 396, .adv_w = 96, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 403, .adv_w = 129, .box_w = 8, .box_h = 4, .ofs_x = 0, .ofs_y = 1}
};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_0[] = {
    0x0, 0x7, 0xa, 0xb, 0xc, 0x10, 0x12, 0x14,
    0x18, 0x1b, 0x20, 0x25, 0x26, 0x27, 0x3d, 0x42,
    0x47, 0x4a, 0x4b, 0x4c, 0x50, 0x51, 0x52, 0x53,
    0x66, 0x67, 0x6d, 0x6f, 0x70, 0x73, 0x76, 0x77,
    0x78, 0x7a, 0x92, 0x94, 0xc3, 0xc4, 0xc6, 0xc8,
    0xdf, 0xe6, 0xe9, 0xf2, 0x11b, 0x123, 0x15a, 0x1ea,
    0x23f, 0x240, 0x241, 0x242, 0x243, 0x286, 0x292, 0x2ec,
    0x303, 0x559, 0x7c1, 0x8a1
};

/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 61441, .range_length = 2210, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = 60, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};



/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};



/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t lv_font_eink_symbols_8 = {
#else
lv_font_t lv_font_eink_symbols_8 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = 8,          /*The maximum line height required by the font*/
    .base_line = 1,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -3,
    .underline_thickness = 0,
#endif
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};



#endif /*#if LV_FONT_EINK_SYMBOLS_8*/

