/* Generated by tools/gen_eink_fonts.py -- do not edit.
 * Terminus Medium 12 px (ter-u12n.bdf), 1 bpp, standing in
 * as lv_font_montserrat_8 on the T-Deck Pro's e-paper; line metrics
 * 12/2 (Montserrat's were 10/2). Icons fall back to
 * lv_font_eink_symbols_8.
 * Terminus Font: Copyright (C) 2020 Dimitar Toshkov Zhekov, SIL OFL 1.1
 * (see OFL-Terminus.txt). */

#include <lvgl.h>

LV_FONT_DECLARE(lv_font_eink_symbols_8)

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */
    /* U+0021 "!" */
    0xfb,
    /* U+0022 "\"" */
    0xb6, 0x80,
    /* U+0023 "#" */
    0x52, 0xbe, 0xa5, 0x7d, 0x4a,
    /* U+0024 "$" */
    0x23, 0xab, 0x47, 0x16, 0xae, 0x20,
    /* U+0025 "%" */
    0x4a, 0xa5, 0x04, 0x20, 0xa5, 0x52,
    /* U+0026 "&" */
    0x22, 0x94, 0x46, 0xca, 0x4d,
    /* U+0027 "'" */
    0xe0,
    /* U+0028 "(" */
    0x2a, 0x49, 0x11,
    /* U+0029 ")" */
    0x88, 0x92, 0x54,
    /* U+002A "*" */
    0x51, 0x3e, 0x45, 0x00,
    /* U+002B "+" */
    0x21, 0x3e, 0x42, 0x00,
    /* U+002C "," */
    0x58,
    /* U+002D "-" */
    0xf8,
    /* U+002E "." */
    0xc0,
    /* U+002F "/" */
    0x11, 0x22, 0x44, 0x88,
    /* U+0030 "0" */
    0x74, 0x67, 0x5c, 0xc6, 0x2e,
    /* U+0031 "1" */
    0x59, 0x24, 0x97,
    /* U+0032 "2" */
    0x74, 0x62, 0x11, 0x11, 0x1f,
    /* U+0033 "3" */
    0x74, 0x42, 0x60, 0x86, 0x2e,
    /* U+0034 "4" */
    0x08, 0xca, 0x98, 0xfc, 0x21,
    /* U+0035 "5" */
    0xfc, 0x21, 0xe0, 0x86, 0x2e,
    /* U+0036 "6" */
    0x74, 0x21, 0xe8, 0xc6, 0x2e,
    /* U+0037 "7" */
    0xf8, 0x42, 0x21, 0x10, 0x84,
    /* U+0038 "8" */
    0x74, 0x62, 0xe8, 0xc6, 0x2e,
    /* U+0039 "9" */
    0x74, 0x63, 0x17, 0x84, 0x2e,
    /* U+003A ":" */
    0xcc,
    /* U+003B ";" */
    0x50, 0x58,
    /* U+003C "<" */
    0x12, 0x48, 0x42, 0x10,
    /* U+003D "=" */
    0xf8, 0x01, 0xf0,
    /* U+003E ">" */
    0x84, 0x21, 0x24, 0x80,
    /* U+003F "?" */
    0x74, 0x62, 0x22, 0x00, 0x84,
    /* U+0040 "@" */
    0x74, 0x67, 0x5a, 0xce, 0x0f,
    /* U+0041 "A" */
    0x74, 0x63, 0x1f, 0xc6, 0x31,
    /* U+0042 "B" */
    0xf4, 0x63, 0xe8, 0xc6, 0x3e,
    /* U+0043 "C" */
    0x74, 0x61, 0x08, 0x42, 0x2e,
    /* U+0044 "D" */
    0xe4, 0xa3, 0x18, 0xc6, 0x5c,
    /* U+0045 "E" */
    0xfc, 0x21, 0xe8, 0x42, 0x1f,
    /* U+0046 "F" */
    0xfc, 0x21, 0xe8, 0x42, 0x10,
    /* U+0047 "G" */
    0x74, 0x61, 0x0b, 0xc6, 0x2e,
    /* U+0048 "H" */
    0x8c, 0x63, 0xf8, 0xc6, 0x31,
    /* U+0049 "I" */
    0xe9, 0x24, 0x97,
    /* U+004A "J" */
    0x38, 0x84, 0x21, 0x4a, 0x4c,
    /* U+004B "K" */
    0x8c, 0xa9, 0x8c, 0x52, 0x51,
    /* U+004C "L" */
    0x84, 0x21, 0x08, 0x42, 0x1f,
    /* U+004D "M" */
    0x8e, 0xeb, 0x58, 0xc6, 0x31,
    /* U+004E "N" */
    0x8c, 0x73, 0x59, 0xc6, 0x31,
    /* U+004F "O" */
    0x74, 0x63, 0x18, 0xc6, 0x2e,
    /* U+0050 "P" */
    0xf4, 0x63, 0x1f, 0x42, 0x10,
    /* U+0051 "Q" */
    0x74, 0x63, 0x18, 0xc6, 0xae, 0x08,
    /* U+0052 "R" */
    0xf4, 0x63, 0x1f, 0x52, 0x51,
    /* U+0053 "S" */
    0x74, 0x60, 0xe0, 0x86, 0x2e,
    /* U+0054 "T" */
    0xf9, 0x08, 0x42, 0x10, 0x84,
    /* U+0055 "U" */
    0x8c, 0x63, 0x18, 0xc6, 0x2e,
    /* U+0056 "V" */
    0x8c, 0x62, 0xa5, 0x28, 0x84,
    /* U+0057 "W" */
    0x8c, 0x63, 0x1a, 0xd7, 0x71,
    /* U+0058 "X" */
    0x8c, 0x54, 0x42, 0x2a, 0x31,
    /* U+0059 "Y" */
    0x8c, 0x54, 0xa2, 0x10, 0x84,
    /* U+005A "Z" */
    0xf8, 0x44, 0x44, 0x42, 0x1f,
    /* U+005B "[" */
    0xf2, 0x49, 0x27,
    /* U+005C "\\" */
    0x88, 0x44, 0x22, 0x11,
    /* U+005D "]" */
    0xe4, 0x92, 0x4f,
    /* U+005E "^" */
    0x22, 0xa2,
    /* U+005F "_" */
    0xf8,
    /* U+0060 "`" */
    0x90,
    /* U+0061 "a" */
    0x70, 0x5f, 0x18, 0xbc,
    /* U+0062 "b" */
    0x84, 0x3d, 0x18, 0xc6, 0x3e,
    /* U+0063 "c" */
    0x74, 0x61, 0x08, 0xb8,
    /* U+0064 "d" */
    0x08, 0x5f, 0x18, 0xc6, 0x2f,
    /* U+0065 "e" */
    0x74, 0x7f, 0x08, 0x3c,
    /* U+0066 "f" */
    0x34, 0xe4, 0x44, 0x44,
    /* U+0067 "g" */
    0x7c, 0x63, 0x18, 0xbc, 0x2e,
    /* U+0068 "h" */
    0x84, 0x3d, 0x18, 0xc6, 0x31,
    /* U+0069 "i" */
    0x48, 0x64, 0x92, 0xe0,
    /* U+006A "j" */
    0x11, 0x03, 0x11, 0x11, 0x19, 0x60,
    /* U+006B "k" */
    0x88, 0x9a, 0xcc, 0xa9,
    /* U+006C "l" */
    0xc9, 0x24, 0x97,
    /* U+006D "m" */
    0xf5, 0x6b, 0x5a, 0xd4,
    /* U+006E "n" */
    0xf4, 0x63, 0x18, 0xc4,
    /* U+006F "o" */
    0x74, 0x63, 0x18, 0xb8,
    /* U+0070 "p" */
    0xf4, 0x63, 0x18, 0xfa, 0x10,
    /* U+0071 "q" */
    0x7c, 0x63, 0x18, 0xbc, 0x21,
    /* U+0072 "r" */
    0xbe, 0x21, 0x08, 0x40,
    /* U+0073 "s" */
    0x7c, 0x1c, 0x10, 0xf8,
    /* U+0074 "t" */
    0x44, 0xe4, 0x44, 0x43,
    /* U+0075 "u" */
    0x8c, 0x63, 0x18, 0xbc,
    /* U+0076 "v" */
    0x8c, 0x54, 0xa2, 0x10,
    /* U+0077 "w" */
    0x8c, 0x6b, 0x5a, 0xb8,
    /* U+0078 "x" */
    0x8a, 0x88, 0x45, 0x44,
    /* U+0079 "y" */
    0x8c, 0x63, 0x18, 0xbc, 0x2e,
    /* U+007A "z" */
    0xf8, 0x88, 0x88, 0x7c,
    /* U+007B "{" */
    0x34, 0x48, 0x44, 0x43,
    /* U+007C "|" */
    0xff,
    /* U+007D "}" */
    0xc2, 0x21, 0x22, 0x2c,
    /* U+007E "~" */
    0x4d, 0x64,
    /* U+00A0 " " */
    /* U+00A1 "¡" */
    0xdf,
    /* U+00A2 "¢" */
    0x23, 0xab, 0x4a, 0x55, 0xc4,
    /* U+00A3 "£" */
    0x32, 0x51, 0xe4, 0x21, 0x3f,
    /* U+00A4 "¤" */
    0x96, 0x99, 0x69,
    /* U+00A5 "¥" */
    0x8c, 0x54, 0x47, 0x11, 0xc4,
    /* U+00A6 "¦" */
    0xe7,
    /* U+00A7 "§" */
    0x69, 0x4a, 0x95, 0x29, 0x60,
    /* U+00A8 "¨" */
    0xb4,
    /* U+00A9 "©" */
    0x7a, 0x1b, 0x69, 0xa6, 0xd8, 0x5e,
    /* U+00AA "ª" */
    0x61, 0x79, 0x70, 0xf0,
    /* U+00AB "«" */
    0x14, 0xa5, 0x28, 0x50, 0xa1, 0x40,
    /* U+00AC "¬" */
    0xf8, 0x42, 0x10,
    /* U+00AD "­" */
    0xf0,
    /* U+00AE "®" */
    0x7a, 0x1b, 0x6b, 0xb6, 0xb8, 0x5e,
    /* U+00AF "¯" */
    0xe0,
    /* U+00B0 "°" */
    0x55, 0x00,
    /* U+00B1 "±" */
    0x21, 0x3e, 0x42, 0x03, 0xe0,
    /* U+00B2 "²" */
    0x69, 0x24, 0xf0,
    /* U+00B3 "³" */
    0xe1, 0x61, 0xe0,
    /* U+00B4 "´" */
    0x60,
    /* U+00B5 "µ" */
    0x8c, 0x63, 0x19, 0xf6, 0x10,
    /* U+00B6 "¶" */
    0x7d, 0x6b, 0x56, 0x94, 0xa5,
    /* U+00B7 "·" */
    0xc0,
    /* U+00B8 "¸" */
    0x58,
    /* U+00B9 "¹" */
    0x59, 0x2e,
    /* U+00BA "º" */
    0x69, 0x99, 0x60, 0xf0,
    /* U+00BB "»" */
    0xa1, 0x42, 0x85, 0x29, 0x4a, 0x00,
    /* U+00BC "¼" */
    0x43, 0x04, 0x52, 0x50, 0x84, 0xa6, 0x29, 0xe0, 0x82,
    /* U+00BD "½" */
    0x43, 0x04, 0x52, 0x50, 0x84, 0x26, 0x24, 0x21, 0x0f,
    /* U+00BE "¾" */
    0xe0, 0x46, 0x05, 0xe8, 0x42, 0x53, 0x94, 0xf0, 0x41,
    /* U+00BF "¿" */
    0x21, 0x00, 0x44, 0x46, 0x2e,
    /* U+00C0 "À" */
    0x41, 0x1d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C1 "Á" */
    0x11, 0x1d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C2 "Â" */
    0x22, 0x9d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C3 "Ã" */
    0x2a, 0x9d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C4 "Ä" */
    0x52, 0x9d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C5 "Å" */
    0x22, 0x9d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+00C6 "Æ" */
    0x7e, 0x49, 0x3f, 0x92, 0x49, 0x27,
    /* U+00C7 "Ç" */
    0x74, 0x61, 0x08, 0x42, 0x2e, 0x22, 0x00,
    /* U+00C8 "È" */
    0x41, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+00C9 "É" */
    0x11, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+00CA "Ê" */
    0x22, 0xbf, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+00CB "Ë" */
    0x52, 0xbf, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+00CC "Ì" */
    0x8b, 0xa4, 0x92, 0x5c,
    /* U+00CD "Í" */
    0x2b, 0xa4, 0x92, 0x5c,
    /* U+00CE "Î" */
    0x57, 0xa4, 0x92, 0x5c,
    /* U+00CF "Ï" */
    0xb7, 0xa4, 0x92, 0x5c,
    /* U+00D0 "Ð" */
    0xe4, 0xa3, 0xd8, 0xc6, 0x5c,
    /* U+00D1 "Ñ" */
    0x2a, 0xa3, 0x1c, 0xd6, 0x71, 0x8c, 0x40,
    /* U+00D2 "Ò" */
    0x41, 0x1d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00D3 "Ó" */
    0x11, 0x1d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00D4 "Ô" */
    0x22, 0x9d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00D5 "Õ" */
    0x2a, 0x9d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00D6 "Ö" */
    0x52, 0x9d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00D7 "×" */
    0x8a, 0x88, 0xa8, 0x80,
    /* U+00D8 "Ø" */
    0x76, 0x29, 0xaa, 0xca, 0x28, 0x9c,
    /* U+00D9 "Ù" */
    0x41, 0x23, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00DA "Ú" */
    0x11, 0x23, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00DB "Û" */
    0x22, 0xa3, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00DC "Ü" */
    0x52, 0xa3, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+00DD "Ý" */
    0x11, 0x23, 0x15, 0x28, 0x84, 0x21, 0x00,
    /* U+00DE "Þ" */
    0x87, 0xa3, 0x18, 0xfa, 0x10,
    /* U+00DF "ß" */
    0xe4, 0xa5, 0xe8, 0xc7, 0x36,
    /* U+00E0 "à" */
    0x41, 0x1c, 0x17, 0xc6, 0x2f,
    /* U+00E1 "á" */
    0x11, 0x1c, 0x17, 0xc6, 0x2f,
    /* U+00E2 "â" */
    0x22, 0x9c, 0x17, 0xc6, 0x2f,
    /* U+00E3 "ã" */
    0x2a, 0x9c, 0x17, 0xc6, 0x2f,
    /* U+00E4 "ä" */
    0x52, 0x9c, 0x17, 0xc6, 0x2f,
    /* U+00E5 "å" */
    0x22, 0x9c, 0x17, 0xc6, 0x2f,
    /* U+00E6 "æ" */
    0x71, 0x5b, 0x6a, 0x3c,
    /* U+00E7 "ç" */
    0x74, 0x61, 0x08, 0xb8, 0x88,
    /* U+00E8 "è" */
    0x41, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+00E9 "é" */
    0x11, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+00EA "ê" */
    0x22, 0x9d, 0x1f, 0xc2, 0x0f,
    /* U+00EB "ë" */
    0x52, 0x9d, 0x1f, 0xc2, 0x0f,
    /* U+00EC "ì" */
    0x8b, 0x24, 0x97,
    /* U+00ED "í" */
    0x2b, 0x24, 0x97,
    /* U+00EE "î" */
    0x57, 0x24, 0x97,
    /* U+00EF "ï" */
    0xb7, 0x24, 0x97,
    /* U+00F0 "ð" */
    0xa2, 0x28, 0xe8, 0xc6, 0x31, 0x70,
    /* U+00F1 "ñ" */
    0x2a, 0xbd, 0x18, 0xc6, 0x31,
    /* U+00F2 "ò" */
    0x41, 0x1d, 0x18, 0xc6, 0x2e,
    /* U+00F3 "ó" */
    0x11, 0x1d, 0x18, 0xc6, 0x2e,
    /* U+00F4 "ô" */
    0x22, 0x9d, 0x18, 0xc6, 0x2e,
    /* U+00F5 "õ" */
    0x2a, 0x9d, 0x18, 0xc6, 0x2e,
    /* U+00F6 "ö" */
    0x52, 0x9d, 0x18, 0xc6, 0x2e,
    /* U+00F7 "÷" */
    0x21, 0x01, 0xf0, 0x10, 0x80,
    /* U+00F8 "ø" */
    0x76, 0x6a, 0xb2, 0x89, 0xc0,
    /* U+00F9 "ù" */
    0x41, 0x23, 0x18, 0xc6, 0x2f,
    /* U+00FA "ú" */
    0x11, 0x23, 0x18, 0xc6, 0x2f,
    /* U+00FB "û" */
    0x22, 0xa3, 0x18, 0xc6, 0x2f,
    /* U+00FC "ü" */
    0x52, 0xa3, 0x18, 0xc6, 0x2f,
    /* U+00FD "ý" */
    0x11, 0x23, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+00FE "þ" */
    0x84, 0x3d, 0x18, 0xc6, 0x3e, 0x84, 0x00,
    /* U+00FF "ÿ" */
    0x52, 0xa3, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+0100 "Ā" */
    0x70, 0x1d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+0101 "ā" */
    0x70, 0x1c, 0x17, 0xc6, 0x2f,
    /* U+0102 "Ă" */
    0x51, 0x1d, 0x18, 0xc7, 0xf1, 0x8c, 0x40,
    /* U+0103 "ă" */
    0x51, 0x1c, 0x17, 0xc6, 0x2f,
    /* U+0104 "Ą" */
    0x72, 0x28, 0xa2, 0xfa, 0x28, 0xa2, 0x10, 0x30,
    /* U+0105 "ą" */
    0x70, 0x27, 0xa2, 0x89, 0xe1, 0x03,
    /* U+0106 "Ć" */
    0x11, 0x1d, 0x18, 0x42, 0x10, 0x8b, 0x80,
    /* U+0107 "ć" */
    0x11, 0x1d, 0x18, 0x42, 0x2e,
    /* U+0108 "Ĉ" */
    0x22, 0x9d, 0x18, 0x42, 0x10, 0x8b, 0x80,
    /* U+0109 "ĉ" */
    0x22, 0x9d, 0x18, 0x42, 0x2e,
    /* U+010A "Ċ" */
    0x21, 0x1d, 0x18, 0x42, 0x10, 0x8b, 0x80,
    /* U+010B "ċ" */
    0x21, 0x1d, 0x18, 0x42, 0x2e,
    /* U+010C "Č" */
    0x51, 0x1d, 0x18, 0x42, 0x10, 0x8b, 0x80,
    /* U+010D "č" */
    0x51, 0x1d, 0x18, 0x42, 0x2e,
    /* U+010E "Ď" */
    0xa2, 0x39, 0x28, 0xc6, 0x31, 0x97, 0x00,
    /* U+010F "ď" */
    0x51, 0x02, 0x17, 0xc6, 0x31, 0x8b, 0xc0,
    /* U+0110 "Đ" */
    0xe4, 0xa3, 0xd8, 0xc6, 0x5c,
    /* U+0111 "đ" */
    0x08, 0xf0, 0x9e, 0x8a, 0x28, 0x9e,
    /* U+0112 "Ē" */
    0x70, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+0113 "ē" */
    0x70, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+0114 "Ĕ" */
    0x51, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+0115 "ĕ" */
    0x51, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+0116 "Ė" */
    0x21, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+0117 "ė" */
    0x21, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+0118 "Ę" */
    0xfa, 0x08, 0x3c, 0x82, 0x08, 0x3e, 0x10, 0x30,
    /* U+0119 "ę" */
    0x74, 0x7f, 0x08, 0x3c, 0x83,
    /* U+011A "Ě" */
    0x51, 0x3f, 0x08, 0x7a, 0x10, 0x87, 0xc0,
    /* U+011B "ě" */
    0x51, 0x1d, 0x1f, 0xc2, 0x0f,
    /* U+011C "Ĝ" */
    0x22, 0x9d, 0x18, 0x42, 0xf1, 0x8b, 0x80,
    /* U+011D "ĝ" */
    0x22, 0x9f, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+011E "Ğ" */
    0x51, 0x1d, 0x18, 0x42, 0xf1, 0x8b, 0x80,
    /* U+011F "ğ" */
    0x51, 0x1f, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+0120 "Ġ" */
    0x21, 0x1d, 0x18, 0x42, 0xf1, 0x8b, 0x80,
    /* U+0121 "ġ" */
    0x21, 0x1f, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+0122 "Ģ" */
    0x74, 0x61, 0x0b, 0xc6, 0x2e, 0x22, 0x00,
    /* U+0123 "ģ" */
    0x11, 0x1f, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+0124 "Ĥ" */
    0x22, 0xa3, 0x18, 0xfe, 0x31, 0x8c, 0x40,
    /* U+0125 "ĥ" */
    0x22, 0xa1, 0x0f, 0x46, 0x31, 0x8c, 0x40,
    /* U+0126 "Ħ" */
    0x4b, 0xf4, 0x9e, 0x49, 0x24, 0x92,
    /* U+0127 "ħ" */
    0x47, 0x90, 0xe4, 0xa5, 0x29,
    /* U+0128 "Ĩ" */
    0x5a, 0xe4, 0x44, 0x44, 0x4e,
    /* U+0129 "ĩ" */
    0x5a, 0xc4, 0x44, 0x4e,
    /* U+012A "Ī" */
    0xe3, 0xa4, 0x92, 0x5c,
    /* U+012B "ī" */
    0xe3, 0x24, 0x97,
    /* U+012C "Ĭ" */
    0xab, 0xa4, 0x92, 0x5c,
    /* U+012D "ĭ" */
    0xab, 0x24, 0x97,
    /* U+012E "Į" */
    0xe4, 0x44, 0x44, 0x4e, 0x43,
    /* U+012F "į" */
    0x44, 0x0c, 0x44, 0x44, 0xe4, 0x30,
    /* U+0130 "İ" */
    0x4b, 0xa4, 0x92, 0x5c,
    /* U+0131 "ı" */
    0xc9, 0x25, 0xc0,
    /* U+0132 "Ĳ" */
    0x8c, 0x63, 0x18, 0xd6, 0xb2,
    /* U+0133 "ĳ" */
    0x8c, 0x41, 0x38, 0xc6, 0x31, 0x89, 0x44,
    /* U+0134 "Ĵ" */
    0x11, 0x4e, 0x21, 0x08, 0x52, 0x93, 0x00,
    /* U+0135 "ĵ" */
    0x11, 0x4c, 0x21, 0x08, 0x42, 0x93, 0x00,
    /* U+0136 "Ķ" */
    0x8c, 0xa9, 0x8c, 0x52, 0x55, 0x22, 0x00,
    /* U+0137 "ķ" */
    0x88, 0x9a, 0xcc, 0xad, 0x48,
    /* U+0138 "ĸ" */
    0x9a, 0xcc, 0xa9,
    /* U+0139 "Ĺ" */
    0x22, 0x21, 0x08, 0x42, 0x10, 0x87, 0xc0,
    /* U+013A "ĺ" */
    0x2b, 0x24, 0x92, 0x5c,
    /* U+013B "Ļ" */
    0x84, 0x21, 0x08, 0x42, 0x1f, 0x22, 0x00,
    /* U+013C "ļ" */
    0xc9, 0x24, 0x97, 0x50,
    /* U+013D "Ľ" */
    0x51, 0x21, 0x08, 0x42, 0x10, 0x87, 0xc0,
    /* U+013E "ľ" */
    0xab, 0x24, 0x92, 0x5c,
    /* U+013F "Ŀ" */
    0x84, 0x21, 0x29, 0x42, 0x1f,
    /* U+0140 "ŀ" */
    0xc2, 0x10, 0x94, 0xa1, 0x1c,
    /* U+0141 "Ł" */
    0x41, 0x04, 0x18, 0xc1, 0x04, 0x1f,
    /* U+0142 "ł" */
    0xc9, 0x3c, 0x97,
    /* U+0143 "Ń" */
    0x11, 0x23, 0x1c, 0xd6, 0x71, 0x8c, 0x40,
    /* U+0144 "ń" */
    0x11, 0x3d, 0x18, 0xc6, 0x31,
    /* U+0145 "Ņ" */
    0x8c, 0x73, 0x59, 0xc6, 0x35, 0x22, 0x00,
    /* U+0146 "ņ" */
    0xf4, 0x63, 0x18, 0xd4, 0x88,
    /* U+0147 "Ň" */
    0x51, 0x23, 0x1c, 0xd6, 0x71, 0x8c, 0x40,
    /* U+0148 "ň" */
    0x51, 0x3d, 0x18, 0xc6, 0x31,
    /* U+0149 "ŉ" */
    0x42, 0x21, 0xe8, 0xc6, 0x31, 0x88,
    /* U+014A "Ŋ" */
    0x8c, 0x73, 0x59, 0xc6, 0x31, 0x08, 0x80,
    /* U+014B "ŋ" */
    0xf4, 0x63, 0x18, 0xc4, 0x22,
    /* U+014C "Ō" */
    0x70, 0x1d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+014D "ō" */
    0x70, 0x1d, 0x18, 0xc6, 0x2e,
    /* U+014E "Ŏ" */
    0x51, 0x1d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+014F "ŏ" */
    0x51, 0x1d, 0x18, 0xc6, 0x2e,
    /* U+0150 "Ő" */
    0x2a, 0x9d, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+0151 "ő" */
    0x2a, 0x9d, 0x18, 0xc6, 0x2e,
    /* U+0152 "Œ" */
    0x7e, 0x49, 0x27, 0x92, 0x49, 0x1f,
    /* U+0153 "œ" */
    0x75, 0x6b, 0x6a, 0x3c,
    /* U+0154 "Ŕ" */
    0x11, 0x3d, 0x18, 0xc7, 0xd4, 0x94, 0x40,
    /* U+0155 "ŕ" */
    0x11, 0x2f, 0x88, 0x42, 0x10,
    /* U+0156 "Ŗ" */
    0xf4, 0x63, 0x1f, 0x52, 0x55, 0x22, 0x00,
    /* U+0157 "ŗ" */
    0xbe, 0x21, 0x08, 0x61, 0x10,
    /* U+0158 "Ř" */
    0x51, 0x3d, 0x18, 0xc7, 0xd4, 0x94, 0x40,
    /* U+0159 "ř" */
    0x51, 0x2f, 0x88, 0x42, 0x10,
    /* U+015A "Ś" */
    0x11, 0x1d, 0x18, 0x38, 0x21, 0x8b, 0x80,
    /* U+015B "ś" */
    0x11, 0x1f, 0x07, 0x04, 0x3e,
    /* U+015C "Ŝ" */
    0x22, 0x9d, 0x18, 0x38, 0x21, 0x8b, 0x80,
    /* U+015D "ŝ" */
    0x22, 0x9f, 0x07, 0x04, 0x3e,
    /* U+015E "Ş" */
    0x74, 0x60, 0xe0, 0x86, 0x2e, 0x22, 0x00,
    /* U+015F "ş" */
    0x7c, 0x1c, 0x10, 0xf8, 0x88,
    /* U+0160 "Š" */
    0x51, 0x1d, 0x18, 0x38, 0x21, 0x8b, 0x80,
    /* U+0161 "š" */
    0x51, 0x1f, 0x07, 0x04, 0x3e,
    /* U+0162 "Ţ" */
    0xf9, 0x08, 0x42, 0x10, 0x86, 0x11, 0x00,
    /* U+0163 "ţ" */
    0x44, 0xe4, 0x44, 0x43, 0x24,
    /* U+0164 "Ť" */
    0x51, 0x3e, 0x42, 0x10, 0x84, 0x21, 0x00,
    /* U+0165 "ť" */
    0xa4, 0x44, 0xe4, 0x44, 0x43,
    /* U+0166 "Ŧ" */
    0xf9, 0x08, 0xe2, 0x10, 0x84,
    /* U+0167 "ŧ" */
    0x44, 0xe4, 0xe4, 0x43,
    /* U+0168 "Ũ" */
    0x2a, 0xa3, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+0169 "ũ" */
    0x2a, 0xa3, 0x18, 0xc6, 0x2f,
    /* U+016A "Ū" */
    0x70, 0x23, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+016B "ū" */
    0x70, 0x23, 0x18, 0xc6, 0x2f,
    /* U+016C "Ŭ" */
    0x51, 0x23, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+016D "ŭ" */
    0x51, 0x23, 0x18, 0xc6, 0x2f,
    /* U+016E "Ů" */
    0x22, 0xab, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+016F "ů" */
    0x22, 0xab, 0x18, 0xc6, 0x2f,
    /* U+0170 "Ű" */
    0x2a, 0xa3, 0x18, 0xc6, 0x31, 0x8b, 0x80,
    /* U+0171 "ű" */
    0x2a, 0xa3, 0x18, 0xc6, 0x2f,
    /* U+0172 "Ų" */
    0x8c, 0x63, 0x18, 0xc6, 0x2e, 0x20, 0xc0,
    /* U+0173 "ų" */
    0x8a, 0x28, 0xa2, 0x89, 0xe1, 0x03,
    /* U+0174 "Ŵ" */
    0x22, 0xa3, 0x18, 0xc6, 0xb5, 0xdc, 0x40,
    /* U+0175 "ŵ" */
    0x22, 0xa3, 0x1a, 0xd6, 0xae,
    /* U+0176 "Ŷ" */
    0x22, 0xa3, 0x15, 0x28, 0x84, 0x21, 0x00,
    /* U+0177 "ŷ" */
    0x22, 0xa3, 0x18, 0xc6, 0x2f, 0x0b, 0x80,
    /* U+0178 "Ÿ" */
    0x52, 0xa3, 0x15, 0x28, 0x84, 0x21, 0x00,
    /* U+0179 "Ź" */
    0x11, 0x3e, 0x11, 0x11, 0x10, 0x87, 0xc0,
    /* U+017A "ź" */
    0x11, 0x3e, 0x22, 0x22, 0x1f,
    /* U+017B "Ż" */
    0x21, 0x3e, 0x11, 0x11, 0x10, 0x87, 0xc0,
    /* U+017C "ż" */
    0x21, 0x3e, 0x22, 0x22, 0x1f,
    /* U+017D "Ž" */
    0x51, 0x3e, 0x11, 0x11, 0x10, 0x87, 0xc0,
    /* U+017E "ž" */
    0x51, 0x3e, 0x22, 0x22, 0x1f,
    /* U+017F "ſ" */
    0x72, 0x49, 0x24,
    /* U+0218 "Ș" */
    0x74, 0x60, 0xe0, 0x86, 0x2e, 0x22, 0x00,
    /* U+0219 "ș" */
    0x7c, 0x1c, 0x10, 0xf8, 0x88,
    /* U+021A "Ț" */
    0xf9, 0x08, 0x42, 0x10, 0x86, 0x11, 0x00,
    /* U+021B "ț" */
    0x44, 0xe4, 0x44, 0x43, 0x12,
    /* U+2022 "•" */
    0x6f, 0xf6,
    /* U+20AC "€" */
    0x39, 0x1f, 0x10, 0xf1, 0x13, 0x80,
    0x00 /* keeps the array non-empty */
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 96, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 96, .box_w = 1, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1, .adv_w = 96, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 3, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 8, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 14, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 20, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 25, .adv_w = 96, .box_w = 1, .box_h = 3, .ofs_x = 2, .ofs_y = 6},
    {.bitmap_index = 26, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 29, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 32, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 36, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 40, .adv_w = 96, .box_w = 2, .box_h = 3, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 41, .adv_w = 96, .box_w = 5, .box_h = 1, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 42, .adv_w = 96, .box_w = 1, .box_h = 2, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 43, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 47, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 52, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 55, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 60, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 65, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 70, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 75, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 80, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 85, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 90, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 95, .adv_w = 96, .box_w = 1, .box_h = 6, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 96, .adv_w = 96, .box_w = 2, .box_h = 7, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 98, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 102, .adv_w = 96, .box_w = 5, .box_h = 4, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 105, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 109, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 114, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 119, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 124, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 129, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 134, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 139, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 144, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 149, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 154, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 159, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 162, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 167, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 172, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 177, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 182, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 187, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 192, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 197, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 203, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 208, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 213, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 218, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 223, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 228, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 233, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 238, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 243, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 248, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 251, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 255, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 258, .adv_w = 96, .box_w = 5, .box_h = 3, .ofs_x = 0, .ofs_y = 6},
    {.bitmap_index = 260, .adv_w = 96, .box_w = 5, .box_h = 1, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 261, .adv_w = 96, .box_w = 2, .box_h = 2, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 262, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 266, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 271, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 275, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 280, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 284, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 288, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 293, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 298, .adv_w = 96, .box_w = 3, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 302, .adv_w = 96, .box_w = 4, .box_h = 11, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 308, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 312, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 315, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 319, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 323, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 327, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 332, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 337, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 341, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 345, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 349, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 353, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 357, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 361, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 365, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 370, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 374, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 378, .adv_w = 96, .box_w = 1, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 379, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 383, .adv_w = 96, .box_w = 5, .box_h = 3, .ofs_x = 0, .ofs_y = 6},
    {.bitmap_index = 385, .adv_w = 96, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 385, .adv_w = 96, .box_w = 1, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 386, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 391, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 396, .adv_w = 96, .box_w = 4, .box_h = 6, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 399, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 404, .adv_w = 96, .box_w = 1, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 405, .adv_w = 96, .box_w = 4, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 410, .adv_w = 96, .box_w = 3, .box_h = 2, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 411, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 417, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 421, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 427, .adv_w = 96, .box_w = 5, .box_h = 4, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 430, .adv_w = 96, .box_w = 4, .box_h = 1, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 431, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 437, .adv_w = 96, .box_w = 3, .box_h = 1, .ofs_x = 1, .ofs_y = 9},
    {.bitmap_index = 438, .adv_w = 96, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 440, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 445, .adv_w = 96, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 448, .adv_w = 96, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 451, .adv_w = 96, .box_w = 2, .box_h = 2, .ofs_x = 2, .ofs_y = 8},
    {.bitmap_index = 452, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 457, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 462, .adv_w = 96, .box_w = 1, .box_h = 2, .ofs_x = 2, .ofs_y = 3},
    {.bitmap_index = 463, .adv_w = 96, .box_w = 2, .box_h = 3, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 464, .adv_w = 96, .box_w = 3, .box_h = 5, .ofs_x = 2, .ofs_y = 4},
    {.bitmap_index = 466, .adv_w = 96, .box_w = 4, .box_h = 7, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 470, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 476, .adv_w = 96, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 485, .adv_w = 96, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 494, .adv_w = 96, .box_w = 6, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 503, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 508, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 515, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 522, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 529, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 536, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 543, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 550, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 556, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 563, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 570, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 577, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 584, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 591, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 595, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 599, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 603, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 607, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 612, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 619, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 626, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 633, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 640, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 647, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 654, .adv_w = 96, .box_w = 5, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 658, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 664, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 671, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 678, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 685, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 692, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 699, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 704, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 709, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 714, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 719, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 724, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 729, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 734, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 739, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 743, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 748, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 753, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 758, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 763, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 768, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 771, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 774, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 777, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 780, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 786, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 791, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 796, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 801, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 806, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 811, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 816, .adv_w = 96, .box_w = 5, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 821, .adv_w = 96, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 826, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 831, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 836, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 841, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 846, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 853, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 860, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 867, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 874, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 879, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 886, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 891, .adv_w = 96, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 899, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 905, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 912, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 917, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 924, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 929, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 936, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 941, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 948, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 953, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 960, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 967, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 972, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 978, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 985, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 990, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 997, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1002, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1009, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1014, .adv_w = 96, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1022, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1027, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1034, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1039, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1046, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1053, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1060, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1067, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1074, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1081, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1088, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1095, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1102, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1109, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1115, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1120, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1125, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1129, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1133, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1136, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1140, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1143, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1148, .adv_w = 96, .box_w = 4, .box_h = 11, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1154, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1158, .adv_w = 96, .box_w = 3, .box_h = 6, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1161, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1166, .adv_w = 96, .box_w = 5, .box_h = 11, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1173, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1180, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1187, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1194, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1199, .adv_w = 96, .box_w = 4, .box_h = 6, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1202, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1209, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1213, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1220, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1224, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1231, .adv_w = 96, .box_w = 3, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1235, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1240, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1245, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1251, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1254, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1261, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1266, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1273, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1278, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1285, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1290, .adv_w = 96, .box_w = 5, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1296, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1303, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1308, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1315, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1320, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1327, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1332, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1339, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1344, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1350, .adv_w = 96, .box_w = 5, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1354, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1361, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1366, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1373, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1378, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1385, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1390, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1397, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1402, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1409, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1414, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1421, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1426, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1433, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1438, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1445, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1450, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1457, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1462, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1467, .adv_w = 96, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1471, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1478, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1483, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1490, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1495, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1502, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1507, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1514, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1519, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1526, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1531, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1538, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1544, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1551, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1556, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1563, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1570, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1577, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1584, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1589, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1596, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1601, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1608, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1613, .adv_w = 96, .box_w = 3, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1616, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1623, .adv_w = 96, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1628, .adv_w = 96, .box_w = 5, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1635, .adv_w = 96, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1640, .adv_w = 96, .box_w = 4, .box_h = 4, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 1642, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 32, .range_length = 95, .glyph_id_start = 1,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 160, .range_length = 224, .glyph_id_start = 96,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 536, .range_length = 4, .glyph_id_start = 320,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8226, .range_length = 1, .glyph_id_start = 324,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8364, .range_length = 1, .glyph_id_start = 325,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 5,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t lv_font_montserrat_8 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 12,
    .base_line = 2,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_eink_symbols_8,
    .user_data = NULL,
};
