/* Generated by tools/gen_eink_fonts.py -- do not edit.
 * Terminus Bold, emboldened 1 px, 12 px (ter-u12b.bdf), 1 bpp, standing in
 * as lv_font_eink_bold_12 on the T-Deck Pro's e-paper; line metrics
 * 15/3 (Montserrat's were 15/3). Icons fall back to
 * lv_font_eink_symbols_12.
 * Terminus Font: Copyright (C) 2020 Dimitar Toshkov Zhekov, SIL OFL 1.1
 * (see OFL-Terminus.txt). */

#include <lvgl.h>

LV_FONT_DECLARE(lv_font_eink_symbols_12)

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */
    /* U+0021 "!" */
    0xff, 0xcf,
    /* U+0022 "\"" */
    0xff, 0xf0,
    /* U+0023 "#" */
    0x79, 0xef, 0xde, 0x7b, 0xf7, 0x9e,
    /* U+0024 "$" */
    0x31, 0xef, 0xfc, 0x78, 0xff, 0xde, 0x30,
    /* U+0025 "%" */
    0x6d, 0xf9, 0xe0, 0xc3, 0x07, 0x9f, 0xb6,
    /* U+0026 "&" */
    0x31, 0xe7, 0x8c, 0x7f, 0x6d, 0x9f,
    /* U+0027 "'" */
    0xfc,
    /* U+0028 "(" */
    0x36, 0xcc, 0xcc, 0x63,
    /* U+0029 ")" */
    0xc6, 0x33, 0x33, 0x6c,
    /* U+002A "*" */
    0x78, 0xcf, 0xcc, 0x78,
    /* U+002B "+" */
    0x30, 0xcf, 0xcc, 0x30,
    /* U+002C "," */
    0x6f, 0x00,
    /* U+002D "-" */
    0xfc,
    /* U+002E "." */
    0xf0,
    /* U+002F "/" */
    0x18, 0xcc, 0x66, 0x33, 0x18,
    /* U+0030 "0" */
    0x7b, 0x3d, 0xff, 0xef, 0x3c, 0xde,
    /* U+0031 "1" */
    0x6e, 0x66, 0x66, 0x6f,
    /* U+0032 "2" */
    0x7b, 0x3c, 0xc3, 0x18, 0xc6, 0x3f,
    /* U+0033 "3" */
    0x7b, 0x30, 0xce, 0x0c, 0x3c, 0xde,
    /* U+0034 "4" */
    0x0c, 0x73, 0xdb, 0xcf, 0xf0, 0xc3,
    /* U+0035 "5" */
    0xff, 0x0c, 0x3e, 0x0c, 0x3c, 0xde,
    /* U+0036 "6" */
    0x7b, 0x0c, 0x3e, 0xcf, 0x3c, 0xde,
    /* U+0037 "7" */
    0xfc, 0x30, 0xc6, 0x18, 0xc3, 0x0c,
    /* U+0038 "8" */
    0x7b, 0x3c, 0xde, 0xcf, 0x3c, 0xde,
    /* U+0039 "9" */
    0x7b, 0x3c, 0xf3, 0x7c, 0x30, 0xde,
    /* U+003A ":" */
    0xf0, 0xf0,
    /* U+003B ";" */
    0x6c, 0x06, 0xf0,
    /* U+003C "<" */
    0x19, 0x99, 0x86, 0x18, 0x60,
    /* U+003D "=" */
    0xfc, 0x00, 0x3f,
    /* U+003E ">" */
    0xc3, 0x0c, 0x33, 0x33, 0x00,
    /* U+003F "?" */
    0x7b, 0x3c, 0xc6, 0x30, 0x03, 0x0c,
    /* U+0040 "@" */
    0x7b, 0x3d, 0xff, 0xff, 0x7c, 0x1f,
    /* U+0041 "A" */
    0x7b, 0x3c, 0xf3, 0xff, 0x3c, 0xf3,
    /* U+0042 "B" */
    0xfb, 0x3c, 0xfe, 0xcf, 0x3c, 0xfe,
    /* U+0043 "C" */
    0x7b, 0x3c, 0x30, 0xc3, 0x0c, 0xde,
    /* U+0044 "D" */
    0xf3, 0x6c, 0xf3, 0xcf, 0x3d, 0xbc,
    /* U+0045 "E" */
    0xff, 0x0c, 0x3e, 0xc3, 0x0c, 0x3f,
    /* U+0046 "F" */
    0xff, 0x0c, 0x3e, 0xc3, 0x0c, 0x30,
    /* U+0047 "G" */
    0x7b, 0x3c, 0x30, 0xff, 0x3c, 0xde,
    /* U+0048 "H" */
    0xcf, 0x3c, 0xff, 0xcf, 0x3c, 0xf3,
    /* U+0049 "I" */
    0xf6, 0x66, 0x66, 0x6f,
    /* U+004A "J" */
    0x3c, 0x61, 0x86, 0x1b, 0x6d, 0x9c,
    /* U+004B "K" */
    0xcf, 0x6f, 0x38, 0xe3, 0xcd, 0xb3,
    /* U+004C "L" */
    0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0x3f,
    /* U+004D "M" */
    0xcf, 0xff, 0xff, 0xcf, 0x3c, 0xf3,
    /* U+004E "N" */
    0xcf, 0x3e, 0xff, 0xdf, 0x3c, 0xf3,
    /* U+004F "O" */
    0x7b, 0x3c, 0xf3, 0xcf, 0x3c, 0xde,
    /* U+0050 "P" */
    0xfb, 0x3c, 0xf3, 0xfb, 0x0c, 0x30,
    /* U+0051 "Q" */
    0x7b, 0x3c, 0xf3, 0xcf, 0x3f, 0xde, 0x0c,
    /* U+0052 "R" */
    0xfb, 0x3c, 0xf3, 0xfb, 0xcd, 0xb3,
    /* U+0053 "S" */
    0x7b, 0x3c, 0x1e, 0x0c, 0x3c, 0xde,
    /* U+0054 "T" */
    0xfc, 0xc3, 0x0c, 0x30, 0xc3, 0x0c,
    /* U+0055 "U" */
    0xcf, 0x3c, 0xf3, 0xcf, 0x3c, 0xde,
    /* U+0056 "V" */
    0xcf, 0x3c, 0xde, 0x79, 0xe3, 0x0c,
    /* U+0057 "W" */
    0xcf, 0x3c, 0xf3, 0xff, 0xff, 0xf3,
    /* U+0058 "X" */
    0xcf, 0x37, 0x8c, 0x31, 0xec, 0xf3,
    /* U+0059 "Y" */
    0xcf, 0x37, 0x9e, 0x30, 0xc3, 0x0c,
    /* U+005A "Z" */
    0xfc, 0x31, 0x8c, 0x63, 0x0c, 0x3f,
    /* U+005B "[" */
    0xfc, 0xcc, 0xcc, 0xcf,
    /* U+005C "\\" */
    0xc6, 0x18, 0xc3, 0x18, 0x63,
    /* U+005D "]" */
    0xf3, 0x33, 0x33, 0x3f,
    /* U+005E "^" */
    0x31, 0xec, 0xc0,
    /* U+005F "_" */
    0xfc,
    /* U+0060 "`" */
    0xcc,
    /* U+0061 "a" */
    0x78, 0x37, 0xf3, 0xcd, 0xf0,
    /* U+0062 "b" */
    0xc3, 0x0f, 0xb3, 0xcf, 0x3c, 0xfe,
    /* U+0063 "c" */
    0x7b, 0x3c, 0x30, 0xcd, 0xe0,
    /* U+0064 "d" */
    0x0c, 0x37, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+0065 "e" */
    0x7b, 0x3f, 0xf0, 0xc1, 0xf0,
    /* U+0066 "f" */
    0x3b, 0x3c, 0xc6, 0x31, 0x8c,
    /* U+0067 "g" */
    0x7f, 0x3c, 0xf3, 0xcd, 0xf0, 0xde,
    /* U+0068 "h" */
    0xc3, 0x0f, 0xb3, 0xcf, 0x3c, 0xf3,
    /* U+0069 "i" */
    0x66, 0x0e, 0x66, 0x66, 0xf0,
    /* U+006A "j" */
    0x18, 0xc0, 0x71, 0x8c, 0x63, 0x1e, 0xdc,
    /* U+006B "k" */
    0xc6, 0x37, 0xee, 0x73, 0xdb,
    /* U+006C "l" */
    0xe6, 0x66, 0x66, 0x6f,
    /* U+006D "m" */
    0xfb, 0xff, 0xff, 0xff, 0xf0,
    /* U+006E "n" */
    0xfb, 0x3c, 0xf3, 0xcf, 0x30,
    /* U+006F "o" */
    0x7b, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+0070 "p" */
    0xfb, 0x3c, 0xf3, 0xcf, 0xec, 0x30,
    /* U+0071 "q" */
    0x7f, 0x3c, 0xf3, 0xcd, 0xf0, 0xc3,
    /* U+0072 "r" */
    0xff, 0x8c, 0x30, 0xc3, 0x00,
    /* U+0073 "s" */
    0x7f, 0x07, 0x83, 0x0f, 0xe0,
    /* U+0074 "t" */
    0x63, 0x3c, 0xc6, 0x31, 0x87,
    /* U+0075 "u" */
    0xcf, 0x3c, 0xf3, 0xcd, 0xf0,
    /* U+0076 "v" */
    0xcf, 0x37, 0x9e, 0x30, 0xc0,
    /* U+0077 "w" */
    0xcf, 0x3f, 0xff, 0xfd, 0xe0,
    /* U+0078 "x" */
    0xcd, 0xe3, 0x0c, 0x7b, 0x30,
    /* U+0079 "y" */
    0xcf, 0x3c, 0xf3, 0xcd, 0xf0, 0xde,
    /* U+007A "z" */
    0xfc, 0x63, 0x18, 0xc3, 0xf0,
    /* U+007B "{" */
    0x3b, 0x19, 0x86, 0x31, 0x87,
    /* U+007C "|" */
    0xff, 0xff,
    /* U+007D "}" */
    0xe1, 0x8c, 0x33, 0x18, 0xdc,
    /* U+007E "~" */
    0x6f, 0xfd, 0x80,
    /* U+00A0 " " */
    /* U+00A1 "¡" */
    0xf3, 0xff,
    /* U+00A2 "¢" */
    0x31, 0xef, 0xfc, 0xf3, 0xf7, 0x8c,
    /* U+00A3 "£" */
    0x39, 0xb6, 0x3e, 0x61, 0x86, 0xff,
    /* U+00A4 "¤" */
    0xdb, 0xb7, 0xb7, 0x6c,
    /* U+00A5 "¥" */
    0xcf, 0x37, 0x8c, 0x78, 0xc7, 0x8c,
    /* U+00A6 "¦" */
    0xfc, 0x3f,
    /* U+00A7 "§" */
    0x76, 0xd9, 0xed, 0xbc, 0xdb, 0x70,
    /* U+00A8 "¨" */
    0xff,
    /* U+00A9 "©" */
    0x7d, 0x8f, 0xff, 0xbf, 0x7f, 0xf1, 0xbe,
    /* U+00AA "ª" */
    0x70, 0xdf, 0xb7, 0x83, 0xe0,
    /* U+00AB "«" */
    0x1e, 0x79, 0xe7, 0x87, 0x87, 0x87, 0x80,
    /* U+00AC "¬" */
    0xfc, 0x30, 0xc3,
    /* U+00AD "­" */
    0xf8,
    /* U+00AE "®" */
    0x7d, 0x8f, 0xff, 0xff, 0xff, 0xf1, 0xbe,
    /* U+00AF "¯" */
    0xf0,
    /* U+00B0 "°" */
    0x6f, 0x60,
    /* U+00B1 "±" */
    0x30, 0xcf, 0xcc, 0x30, 0x0f, 0xc0,
    /* U+00B2 "²" */
    0x76, 0xcc, 0xcf, 0x80,
    /* U+00B3 "³" */
    0xf0, 0xdc, 0x3f, 0x00,
    /* U+00B4 "´" */
    0x78,
    /* U+00B5 "µ" */
    0xcf, 0x3c, 0xf3, 0xdf, 0xfc, 0x30,
    /* U+00B6 "¶" */
    0x7f, 0xff, 0xff, 0x7c, 0xf3, 0xcf,
    /* U+00B7 "·" */
    0xf0,
    /* U+00B8 "¸" */
    0x6f, 0x00,
    /* U+00B9 "¹" */
    0x6e, 0x66, 0xf0,
    /* U+00BA "º" */
    0x76, 0xf7, 0xb7, 0x03, 0xe0,
    /* U+00BB "»" */
    0xf0, 0xf0, 0xf0, 0xf3, 0xcf, 0x3c, 0x00,
    /* U+00BC "¼" */
    0x61, 0xc1, 0x9b, 0x67, 0x86, 0x1b, 0x6e, 0x3c, 0xf8, 0x30, 0x60,
    /* U+00BD "½" */
    0x61, 0xc1, 0x9b, 0x67, 0x86, 0x18, 0x6e, 0x36, 0x18, 0x61, 0xf0,
    /* U+00BE "¾" */
    0xf0, 0x31, 0xc0, 0xff, 0xc3, 0x0d, 0xb7, 0xde, 0x7c, 0x18, 0x30,
    /* U+00BF "¿" */
    0x30, 0xc0, 0x0c, 0x63, 0x3c, 0xde,
    /* U+00C0 "À" */
    0x60, 0xc7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C1 "Á" */
    0x18, 0xc7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C2 "Â" */
    0x31, 0xe7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C3 "Ã" */
    0x3d, 0xe7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C4 "Ä" */
    0x79, 0xe7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C5 "Å" */
    0x31, 0xe7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+00C6 "Æ" */
    0x7f, 0xb3, 0x67, 0xfd, 0x9b, 0x36, 0x6f,
    /* U+00C7 "Ç" */
    0x7b, 0x3c, 0x30, 0xc3, 0x0c, 0xde, 0x31, 0x80,
    /* U+00C8 "È" */
    0x60, 0xcf, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+00C9 "É" */
    0x18, 0xcf, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+00CA "Ê" */
    0x31, 0xef, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+00CB "Ë" */
    0x79, 0xef, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+00CC "Ì" */
    0xc6, 0xf6, 0x66, 0x66, 0x6f,
    /* U+00CD "Í" */
    0x36, 0xf6, 0x66, 0x66, 0x6f,
    /* U+00CE "Î" */
    0x6f, 0xf6, 0x66, 0x66, 0x6f,
    /* U+00CF "Ï" */
    0xff, 0xf6, 0x66, 0x66, 0x6f,
    /* U+00D0 "Ð" */
    0xf3, 0x6c, 0xff, 0xcf, 0x3d, 0xbc,
    /* U+00D1 "Ñ" */
    0x3d, 0xec, 0xf3, 0xef, 0xfd, 0xf3, 0xcf, 0x30,
    /* U+00D2 "Ò" */
    0x60, 0xc7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00D3 "Ó" */
    0x18, 0xc7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00D4 "Ô" */
    0x31, 0xe7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00D5 "Õ" */
    0x3d, 0xe7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00D6 "Ö" */
    0x79, 0xe7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00D7 "×" */
    0xcd, 0xe3, 0x1e, 0xcc,
    /* U+00D8 "Ø" */
    0x7f, 0x9b, 0x77, 0xee, 0xd9, 0xb3, 0x3c,
    /* U+00D9 "Ù" */
    0x60, 0xcc, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00DA "Ú" */
    0x18, 0xcc, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00DB "Û" */
    0x31, 0xec, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00DC "Ü" */
    0x79, 0xec, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+00DD "Ý" */
    0x18, 0xcc, 0xf3, 0x79, 0xe3, 0x0c, 0x30, 0xc0,
    /* U+00DE "Þ" */
    0xc3, 0xec, 0xf3, 0xcf, 0xec, 0x30,
    /* U+00DF "ß" */
    0xf3, 0x6d, 0xbe, 0xcf, 0x3e, 0xfe,
    /* U+00E0 "à" */
    0x60, 0xc7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E1 "á" */
    0x18, 0xc7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E2 "â" */
    0x31, 0xe7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E3 "ã" */
    0x3d, 0xe7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E4 "ä" */
    0x79, 0xe7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E5 "å" */
    0x31, 0xe7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+00E6 "æ" */
    0x78, 0xf7, 0xfe, 0xf1, 0xf0,
    /* U+00E7 "ç" */
    0x7b, 0x3c, 0x30, 0xcd, 0xe3, 0x18,
    /* U+00E8 "è" */
    0x60, 0xc7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+00E9 "é" */
    0x18, 0xc7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+00EA "ê" */
    0x31, 0xe7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+00EB "ë" */
    0x79, 0xe7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+00EC "ì" */
    0xc6, 0xe6, 0x66, 0x6f,
    /* U+00ED "í" */
    0x36, 0xe6, 0x66, 0x6f,
    /* U+00EE "î" */
    0x6f, 0xe6, 0x66, 0x6f,
    /* U+00EF "ï" */
    0xff, 0xe6, 0x66, 0x6f,
    /* U+00F0 "ð" */
    0xf1, 0x8f, 0x1e, 0xcf, 0x3c, 0xf3, 0x78,
    /* U+00F1 "ñ" */
    0x3d, 0xef, 0xb3, 0xcf, 0x3c, 0xf3,
    /* U+00F2 "ò" */
    0x60, 0xc7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+00F3 "ó" */
    0x18, 0xc7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+00F4 "ô" */
    0x31, 0xe7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+00F5 "õ" */
    0x3d, 0xe7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+00F6 "ö" */
    0x79, 0xe7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+00F7 "÷" */
    0x30, 0xc0, 0x3f, 0x00, 0xc3, 0x00,
    /* U+00F8 "ø" */
    0x7f, 0xbb, 0xf7, 0x6c, 0xcf, 0x00,
    /* U+00F9 "ù" */
    0x60, 0xcc, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+00FA "ú" */
    0x18, 0xcc, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+00FB "û" */
    0x31, 0xec, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+00FC "ü" */
    0x79, 0xec, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+00FD "ý" */
    0x18, 0xcc, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+00FE "þ" */
    0xc3, 0x0f, 0xb3, 0xcf, 0x3c, 0xfe, 0xc3, 0x00,
    /* U+00FF "ÿ" */
    0x79, 0xec, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+0100 "Ā" */
    0x78, 0x07, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+0101 "ā" */
    0x78, 0x07, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+0102 "Ă" */
    0x78, 0xc7, 0xb3, 0xcf, 0x3f, 0xf3, 0xcf, 0x30,
    /* U+0103 "ă" */
    0x78, 0xc7, 0x83, 0x7f, 0x3c, 0xdf,
    /* U+0104 "Ą" */
    0x79, 0x9b, 0x36, 0x6f, 0xd9, 0xb3, 0x66, 0x18, 0x1c,
    /* U+0105 "ą" */
    0x78, 0x19, 0xf6, 0x6c, 0xcf, 0x86, 0x07,
    /* U+0106 "Ć" */
    0x18, 0xc7, 0xb3, 0xc3, 0x0c, 0x30, 0xcd, 0xe0,
    /* U+0107 "ć" */
    0x18, 0xc7, 0xb3, 0xc3, 0x0c, 0xde,
    /* U+0108 "Ĉ" */
    0x31, 0xe7, 0xb3, 0xc3, 0x0c, 0x30, 0xcd, 0xe0,
    /* U+0109 "ĉ" */
    0x31, 0xe7, 0xb3, 0xc3, 0x0c, 0xde,
    /* U+010A "Ċ" */
    0x30, 0xc7, 0xb3, 0xc3, 0x0c, 0x30, 0xcd, 0xe0,
    /* U+010B "ċ" */
    0x30, 0xc7, 0xb3, 0xc3, 0x0c, 0xde,
    /* U+010C "Č" */
    0x78, 0xc7, 0xb3, 0xc3, 0x0c, 0x30, 0xcd, 0xe0,
    /* U+010D "č" */
    0x78, 0xc7, 0xb3, 0xc3, 0x0c, 0xde,
    /* U+010E "Ď" */
    0xf1, 0x8f, 0x36, 0xcf, 0x3c, 0xf3, 0xdb, 0xc0,
    /* U+010F "ď" */
    0x78, 0xc0, 0xc3, 0x7f, 0x3c, 0xf3, 0xcd, 0xf0,
    /* U+0110 "Đ" */
    0xf3, 0x6c, 0xff, 0xcf, 0x3d, 0xbc,
    /* U+0111 "đ" */
    0x0c, 0x7c, 0x33, 0xec, 0xd9, 0xb3, 0x3e,
    /* U+0112 "Ē" */
    0x78, 0x0f, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+0113 "ē" */
    0x78, 0x07, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+0114 "Ĕ" */
    0x78, 0xcf, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+0115 "ĕ" */
    0x78, 0xc7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+0116 "Ė" */
    0x30, 0xcf, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+0117 "ė" */
    0x30, 0xc7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+0118 "Ę" */
    0xfd, 0x83, 0x07, 0xcc, 0x18, 0x30, 0x7e, 0x18, 0x1c,
    /* U+0119 "ę" */
    0x7b, 0x3f, 0xf0, 0xc1, 0xf3, 0x07,
    /* U+011A "Ě" */
    0x78, 0xcf, 0xf0, 0xc3, 0xec, 0x30, 0xc3, 0xf0,
    /* U+011B "ě" */
    0x78, 0xc7, 0xb3, 0xff, 0x0c, 0x1f,
    /* U+011C "Ĝ" */
    0x31, 0xe7, 0xb3, 0xc3, 0x0f, 0xf3, 0xcd, 0xe0,
    /* U+011D "ĝ" */
    0x31, 0xe7, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+011E "Ğ" */
    0x78, 0xc7, 0xb3, 0xc3, 0x0f, 0xf3, 0xcd, 0xe0,
    /* U+011F "ğ" */
    0x78, 0xc7, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+0120 "Ġ" */
    0x30, 0xc7, 0xb3, 0xc3, 0x0f, 0xf3, 0xcd, 0xe0,
    /* U+0121 "ġ" */
    0x30, 0xc7, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+0122 "Ģ" */
    0x7b, 0x3c, 0x30, 0xff, 0x3c, 0xde, 0x31, 0x80,
    /* U+0123 "ģ" */
    0x18, 0xc7, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+0124 "Ĥ" */
    0x31, 0xec, 0xf3, 0xcf, 0xfc, 0xf3, 0xcf, 0x30,
    /* U+0125 "ĥ" */
    0x31, 0xec, 0x30, 0xfb, 0x3c, 0xf3, 0xcf, 0x30,
    /* U+0126 "Ħ" */
    0x6d, 0xfd, 0xb3, 0xe6, 0xcd, 0x9b, 0x36,
    /* U+0127 "ħ" */
    0x63, 0xe6, 0x1e, 0x6d, 0xb6, 0xdb,
    /* U+0128 "Ĩ" */
    0x7f, 0xbc, 0xc6, 0x31, 0x8c, 0x67, 0x80,
    /* U+0129 "ĩ" */
    0x7f, 0xb8, 0xc6, 0x31, 0x9e,
    /* U+012A "Ī" */
    0xf0, 0xf6, 0x66, 0x66, 0x6f,
    /* U+012B "ī" */
    0xf0, 0xe6, 0x66, 0x6f,
    /* U+012C "Ĭ" */
    0xf6, 0xf6, 0x66, 0x66, 0x6f,
    /* U+012D "ĭ" */
    0xf6, 0xe6, 0x66, 0x6f,
    /* U+012E "Į" */
    0xf3, 0x18, 0xc6, 0x31, 0x9e, 0x61, 0xc0,
    /* U+012F "į" */
    0x63, 0x01, 0xc6, 0x31, 0x8c, 0xf3, 0x0e,
    /* U+0130 "İ" */
    0x66, 0xf6, 0x66, 0x66, 0x6f,
    /* U+0131 "ı" */
    0xe6, 0x66, 0x6f,
    /* U+0132 "Ĳ" */
    0xcf, 0x3c, 0xf3, 0xcf, 0xff, 0xf6,
    /* U+0133 "ĳ" */
    0xcf, 0x30, 0x37, 0xcf, 0x3c, 0xf3, 0xcc, 0xf1, 0x80,
    /* U+0134 "Ĵ" */
    0x18, 0xf3, 0xc6, 0x18, 0x61, 0xb6, 0xd9, 0xc0,
    /* U+0135 "ĵ" */
    0x18, 0xf3, 0x86, 0x18, 0x61, 0x86, 0xd9, 0xc0,
    /* U+0136 "Ķ" */
    0xcf, 0x6f, 0x38, 0xe3, 0xcd, 0xbf, 0x31, 0x80,
    /* U+0137 "ķ" */
    0xc6, 0x37, 0xee, 0x73, 0xdf, 0x66, 0x00,
    /* U+0138 "ĸ" */
    0xdf, 0xb9, 0xcf, 0x6c,
    /* U+0139 "Ĺ" */
    0x31, 0x8c, 0x30, 0xc3, 0x0c, 0x30, 0xc3, 0xf0,
    /* U+013A "ĺ" */
    0x36, 0xe6, 0x66, 0x66, 0x6f,
    /* U+013B "Ļ" */
    0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0x3f, 0x31, 0x80,
    /* U+013C "ļ" */
    0xe6, 0x66, 0x66, 0x6f, 0x6c,
    /* U+013D "Ľ" */
    0x78, 0xcc, 0x30, 0xc3, 0x0c, 0x30, 0xc3, 0xf0,
    /* U+013E "ľ" */
    0xf6, 0xe6, 0x66, 0x66, 0x6f,
    /* U+013F "Ŀ" */
    0xc3, 0x0c, 0x36, 0xdb, 0x0c, 0x3f,
    /* U+0140 "ŀ" */
    0xe1, 0x86, 0x1b, 0x6d, 0x86, 0x3c,
    /* U+0141 "Ł" */
    0x60, 0xc1, 0x83, 0x8e, 0x0c, 0x18, 0x3f,
    /* U+0142 "ł" */
    0xe6, 0x67, 0xe6, 0x6f,
    /* U+0143 "Ń" */
    0x18, 0xcc, 0xf3, 0xef, 0xfd, 0xf3, 0xcf, 0x30,
    /* U+0144 "ń" */
    0x18, 0xcf, 0xb3, 0xcf, 0x3c, 0xf3,
    /* U+0145 "Ņ" */
    0xcf, 0x3e, 0xff, 0xdf, 0x3c, 0xff, 0x31, 0x80,
    /* U+0146 "ņ" */
    0xfb, 0x3c, 0xf3, 0xcf, 0xf3, 0x18,
    /* U+0147 "Ň" */
    0x78, 0xcc, 0xf3, 0xef, 0xfd, 0xf3, 0xcf, 0x30,
    /* U+0148 "ň" */
    0x78, 0xcf, 0xb3, 0xcf, 0x3c, 0xf3,
    /* U+0149 "ŉ" */
    0x61, 0x8c, 0x3e, 0xcf, 0x3c, 0xf3, 0xcc,
    /* U+014A "Ŋ" */
    0xcf, 0x3e, 0xff, 0xdf, 0x3c, 0xf3, 0x0c, 0x60,
    /* U+014B "ŋ" */
    0xfb, 0x3c, 0xf3, 0xcf, 0x30, 0xc6,
    /* U+014C "Ō" */
    0x78, 0x07, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+014D "ō" */
    0x78, 0x07, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+014E "Ŏ" */
    0x78, 0xc7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+014F "ŏ" */
    0x78, 0xc7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+0150 "Ő" */
    0x3d, 0xe7, 0xb3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+0151 "ő" */
    0x3d, 0xe7, 0xb3, 0xcf, 0x3c, 0xde,
    /* U+0152 "Œ" */
    0x7f, 0xb3, 0x66, 0xfd, 0x9b, 0x36, 0x3f,
    /* U+0153 "œ" */
    0x7b, 0xff, 0xfe, 0xf1, 0xf0,
    /* U+0154 "Ŕ" */
    0x18, 0xcf, 0xb3, 0xcf, 0x3f, 0xbc, 0xdb, 0x30,
    /* U+0155 "ŕ" */
    0x18, 0xcf, 0xf8, 0xc3, 0x0c, 0x30,
    /* U+0156 "Ŗ" */
    0xfb, 0x3c, 0xf3, 0xfb, 0xcd, 0xbf, 0x31, 0x80,
    /* U+0157 "ŗ" */
    0xff, 0x8c, 0x30, 0xc3, 0x86, 0x30,
    /* U+0158 "Ř" */
    0x78, 0xcf, 0xb3, 0xcf, 0x3f, 0xbc, 0xdb, 0x30,
    /* U+0159 "ř" */
    0x78, 0xcf, 0xf8, 0xc3, 0x0c, 0x30,
    /* U+015A "Ś" */
    0x18, 0xc7, 0xb3, 0xc1, 0xe0, 0xc3, 0xcd, 0xe0,
    /* U+015B "ś" */
    0x18, 0xc7, 0xf0, 0x78, 0x30, 0xfe,
    /* U+015C "Ŝ" */
    0x31, 0xe7, 0xb3, 0xc1, 0xe0, 0xc3, 0xcd, 0xe0,
    /* U+015D "ŝ" */
    0x31, 0xe7, 0xf0, 0x78, 0x30, 0xfe,
    /* U+015E "Ş" */
    0x7b, 0x3c, 0x1e, 0x0c, 0x3c, 0xde, 0x31, 0x80,
    /* U+015F "ş" */
    0x7f, 0x07, 0x83, 0x0f, 0xe3, 0x18,
    /* U+0160 "Š" */
    0x78, 0xc7, 0xb3, 0xc1, 0xe0, 0xc3, 0xcd, 0xe0,
    /* U+0161 "š" */
    0x78, 0xc7, 0xf0, 0x78, 0x30, 0xfe,
    /* U+0162 "Ţ" */
    0xfc, 0xc3, 0x0c, 0x30, 0xc3, 0x0e, 0x18, 0xc0,
    /* U+0163 "ţ" */
    0x63, 0x3c, 0xc6, 0x31, 0x87, 0x33, 0x00,
    /* U+0164 "Ť" */
    0x78, 0xcf, 0xcc, 0x30, 0xc3, 0x0c, 0x30, 0xc0,
    /* U+0165 "ť" */
    0xf3, 0x18, 0xcf, 0x31, 0x8c, 0x61, 0xc0,
    /* U+0166 "Ŧ" */
    0xfc, 0xc3, 0x1e, 0x30, 0xc3, 0x0c,
    /* U+0167 "ŧ" */
    0x63, 0x3c, 0xcf, 0x31, 0x87,
    /* U+0168 "Ũ" */
    0x3d, 0xec, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+0169 "ũ" */
    0x3d, 0xec, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+016A "Ū" */
    0x78, 0x0c, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+016B "ū" */
    0x78, 0x0c, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+016C "Ŭ" */
    0x78, 0xcc, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+016D "ŭ" */
    0x78, 0xcc, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+016E "Ů" */
    0x31, 0xef, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+016F "ů" */
    0x31, 0xef, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+0170 "Ű" */
    0x3d, 0xec, 0xf3, 0xcf, 0x3c, 0xf3, 0xcd, 0xe0,
    /* U+0171 "ű" */
    0x3d, 0xec, 0xf3, 0xcf, 0x3c, 0xdf,
    /* U+0172 "Ų" */
    0xcf, 0x3c, 0xf3, 0xcf, 0x3c, 0xde, 0x30, 0x70,
    /* U+0173 "ų" */
    0xcd, 0x9b, 0x36, 0x6c, 0xcf, 0x86, 0x07,
    /* U+0174 "Ŵ" */
    0x31, 0xec, 0xf3, 0xcf, 0x3f, 0xff, 0xff, 0x30,
    /* U+0175 "ŵ" */
    0x31, 0xec, 0xf3, 0xff, 0xff, 0xde,
    /* U+0176 "Ŷ" */
    0x31, 0xec, 0xf3, 0x79, 0xe3, 0x0c, 0x30, 0xc0,
    /* U+0177 "ŷ" */
    0x31, 0xec, 0xf3, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0,
    /* U+0178 "Ÿ" */
    0x79, 0xec, 0xf3, 0x79, 0xe3, 0x0c, 0x30, 0xc0,
    /* U+0179 "Ź" */
    0x18, 0xcf, 0xc3, 0x18, 0xc6, 0x30, 0xc3, 0xf0,
    /* U+017A "ź" */
    0x18, 0xcf, 0xc6, 0x31, 0x8c, 0x3f,
    /* U+017B "Ż" */
    0x30, 0xcf, 0xc3, 0x18, 0xc6, 0x30, 0xc3, 0xf0,
    /* U+017C "ż" */
    0x30, 0xcf, 0xc6, 0x31, 0x8c, 0x3f,
    /* U+017D "Ž" */
    0x78, 0xcf, 0xc3, 0x18, 0xc6, 0x30, 0xc3, 0xf0,
    /* U+017E "ž" */
    0x78, 0xcf, 0xc6, 0x31, 0x8c, 0x3f,
    /* U+017F "ſ" */
    0x7c, 0xcc, 0xcc, 0xcc,
    /* U+0218 "Ș" */
    0x7b, 0x3c, 0x1e, 0x0c, 0x3c, 0xde, 0x31, 0x80,
    /* U+0219 "ș" */
    0x7f, 0x07, 0x83, 0x0f, 0xe3, 0x18,
    /* U+021A "Ț" */
    0xfc, 0xc3, 0x0c, 0x30, 0xc3, 0x0e, 0x18, 0xc0,
    /* U+021B "ț" */
    0x63, 0x3c, 0xc6, 0x31, 0x87, 0x19, 0x80,
    /* U+2022 "•" */
    0x77, 0xfe, 0xe0,
    /* U+20AC "€" */
    0x3c, 0xcf, 0xe3, 0x0f, 0x8c, 0xcf, 0x00,
    0x00 /* keeps the array non-empty */
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 112, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 112, .box_w = 2, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2, .adv_w = 112, .box_w = 4, .box_h = 3, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 4, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 10, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 17, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 24, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 30, .adv_w = 112, .box_w = 2, .box_h = 3, .ofs_x = 2, .ofs_y = 6},
    {.bitmap_index = 31, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 35, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 39, .adv_w = 112, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 43, .adv_w = 112, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 47, .adv_w = 112, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 49, .adv_w = 112, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 50, .adv_w = 112, .box_w = 2, .box_h = 2, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 51, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 56, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 62, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 66, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 72, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 78, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 84, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 90, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 96, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 102, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 108, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 114, .adv_w = 112, .box_w = 2, .box_h = 6, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 116, .adv_w = 112, .box_w = 3, .box_h = 7, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 119, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 124, .adv_w = 112, .box_w = 6, .box_h = 4, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 127, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 132, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 138, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 144, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 150, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 156, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 162, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 168, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 174, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 180, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 186, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 192, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 196, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 202, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 208, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 214, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 220, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 226, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 232, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 238, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 245, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 251, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 257, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 263, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 269, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 275, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 281, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 287, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 293, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 299, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 303, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 308, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 312, .adv_w = 112, .box_w = 6, .box_h = 3, .ofs_x = 0, .ofs_y = 6},
    {.bitmap_index = 315, .adv_w = 112, .box_w = 6, .box_h = 1, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 316, .adv_w = 112, .box_w = 3, .box_h = 2, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 317, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 322, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 328, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 333, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 339, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 344, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 349, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 355, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 361, .adv_w = 112, .box_w = 4, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 366, .adv_w = 112, .box_w = 5, .box_h = 11, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 373, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 378, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 382, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 387, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 392, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 397, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 403, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 409, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 414, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 419, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 424, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 429, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 434, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 439, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 444, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 450, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 455, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 460, .adv_w = 112, .box_w = 2, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 462, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 467, .adv_w = 112, .box_w = 6, .box_h = 3, .ofs_x = 0, .ofs_y = 6},
    {.bitmap_index = 470, .adv_w = 112, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 470, .adv_w = 112, .box_w = 2, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 472, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 478, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 484, .adv_w = 112, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 488, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 494, .adv_w = 112, .box_w = 2, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 496, .adv_w = 112, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 502, .adv_w = 112, .box_w = 4, .box_h = 2, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 503, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 510, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 515, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 522, .adv_w = 112, .box_w = 6, .box_h = 4, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 525, .adv_w = 112, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 526, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 533, .adv_w = 112, .box_w = 4, .box_h = 1, .ofs_x = 1, .ofs_y = 9},
    {.bitmap_index = 534, .adv_w = 112, .box_w = 4, .box_h = 3, .ofs_x = 1, .ofs_y = 6},
    {.bitmap_index = 536, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 542, .adv_w = 112, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 546, .adv_w = 112, .box_w = 5, .box_h = 5, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 550, .adv_w = 112, .box_w = 3, .box_h = 2, .ofs_x = 2, .ofs_y = 8},
    {.bitmap_index = 551, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 557, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 563, .adv_w = 112, .box_w = 2, .box_h = 2, .ofs_x = 2, .ofs_y = 3},
    {.bitmap_index = 564, .adv_w = 112, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 566, .adv_w = 112, .box_w = 4, .box_h = 5, .ofs_x = 2, .ofs_y = 4},
    {.bitmap_index = 569, .adv_w = 112, .box_w = 5, .box_h = 7, .ofs_x = 1, .ofs_y = 3},
    {.bitmap_index = 574, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 581, .adv_w = 112, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 592, .adv_w = 112, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 603, .adv_w = 112, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 614, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 620, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 628, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 636, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 644, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 652, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 660, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 668, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 675, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 683, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 691, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 699, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 707, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 715, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 720, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 725, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 730, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 735, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 741, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 749, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 757, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 765, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 773, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 781, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 789, .adv_w = 112, .box_w = 6, .box_h = 5, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 793, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 800, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 808, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 816, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 824, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 832, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 840, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 846, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 852, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 858, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 864, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 870, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 876, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 882, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 888, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 893, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 899, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 905, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 911, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 917, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 923, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 927, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 931, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 935, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 939, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 946, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 952, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 958, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 964, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 970, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 976, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 982, .adv_w = 112, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 988, .adv_w = 112, .box_w = 7, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 994, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1000, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1006, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1012, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1018, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1026, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1034, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1042, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1050, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1056, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1064, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1070, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1079, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1086, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1094, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1100, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1108, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1114, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1122, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1128, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1136, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1142, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1150, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1158, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1164, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1171, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1179, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1185, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1193, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1199, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1207, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1213, .adv_w = 112, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1222, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1228, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1236, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1242, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1250, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1258, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1266, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1274, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1282, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1290, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1298, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1306, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1314, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1322, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1329, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1335, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1342, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1347, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1352, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1356, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1361, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1365, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1372, .adv_w = 112, .box_w = 5, .box_h = 11, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1379, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1384, .adv_w = 112, .box_w = 4, .box_h = 6, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1387, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1393, .adv_w = 112, .box_w = 6, .box_h = 11, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1402, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1410, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1418, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1426, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1433, .adv_w = 112, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1437, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1445, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1450, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1458, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1463, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1471, .adv_w = 112, .box_w = 4, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1476, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1482, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1488, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1495, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1499, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1507, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1513, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1521, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1527, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1535, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1541, .adv_w = 112, .box_w = 6, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1548, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1556, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1562, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1570, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1576, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1584, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1590, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1598, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1604, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1611, .adv_w = 112, .box_w = 6, .box_h = 6, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1616, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1624, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1630, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1638, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1644, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1652, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1658, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1666, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1672, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1680, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1686, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1694, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1700, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1708, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1714, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1722, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1729, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1737, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1744, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1750, .adv_w = 112, .box_w = 5, .box_h = 8, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1755, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1763, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1769, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1777, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1783, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1791, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1797, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1805, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1811, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1819, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1825, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1833, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1840, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1848, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1854, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1862, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1870, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1878, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1886, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1892, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1900, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1906, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1914, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1920, .adv_w = 112, .box_w = 4, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1924, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1932, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1938, .adv_w = 112, .box_w = 6, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1946, .adv_w = 112, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1953, .adv_w = 112, .box_w = 5, .box_h = 4, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 1956, .adv_w = 112, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 32, .range_length = 95, .glyph_id_start = 1,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 160, .range_length = 224, .glyph_id_start = 96,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 536, .range_length = 4, .glyph_id_start = 320,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8226, .range_length = 1, .glyph_id_start = 324,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8364, .range_length = 1, .glyph_id_start = 325,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 5,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t lv_font_eink_bold_12 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 15,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_eink_symbols_12,
    .user_data = NULL,
};
