/* Generated by tools/gen_eink_fonts.py -- do not edit.
 * Terminus Bold 14 px (ter-u14b.bdf), 1 bpp, standing in
 * as lv_font_eink_bold_14 on the T-Deck Pro's e-paper; line metrics
 * 16/3 (Montserrat's were 16/3). Icons fall back to
 * lv_font_eink_symbols_14.
 * Terminus Font: Copyright (C) 2020 Dimitar Toshkov Zhekov, SIL OFL 1.1
 * (see OFL-Terminus.txt). */

#include <lvgl.h>

LV_FONT_DECLARE(lv_font_eink_symbols_14)

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */
    /* U+0021 "!" */
    0xff, 0xfc, 0xf0,
    /* U+0022 "\"" */
    0xcf, 0x3c, 0xc0,
    /* U+0023 "#" */
    0x6c, 0xd9, 0xb7, 0xf6, 0xcd, 0xbf, 0xb6, 0x6c, 0xd8,
    /* U+0024 "$" */
    0x10, 0x21, 0xf6, 0xbd, 0x1a, 0x1f, 0x0b, 0x17, 0xad, 0xf0, 0x81, 0x00,
    /* U+0025 "%" */
    0x66, 0xd6, 0x6c, 0x0c, 0x18, 0x18, 0x30, 0x36, 0x6b, 0x66,
    /* U+0026 "&" */
    0x38, 0xd9, 0xb1, 0xc7, 0x7b, 0xb3, 0x66, 0xdc, 0xec,
    /* U+0027 "'" */
    0xfc,
    /* U+0028 "(" */
    0x36, 0xcc, 0xcc, 0xcc, 0x63,
    /* U+0029 ")" */
    0xc6, 0x33, 0x33, 0x33, 0x6c,
    /* U+002A "*" */
    0x6c, 0x73, 0xf9, 0xc6, 0xc0,
    /* U+002B "+" */
    0x30, 0xcf, 0xcc, 0x30,
    /* U+002C "," */
    0x6f, 0x00,
    /* U+002D "-" */
    0xfe,
    /* U+002E "." */
    0xf0,
    /* U+002F "/" */
    0x0c, 0x31, 0x86, 0x30, 0xc6, 0x18, 0xc3, 0x00,
    /* U+0030 "0" */
    0x7d, 0x8f, 0x1e, 0x7d, 0xfe, 0xf9, 0xe3, 0xc6, 0xf8,
    /* U+0031 "1" */
    0x31, 0xcf, 0x0c, 0x30, 0xc3, 0x0c, 0x33, 0xf0,
    /* U+0032 "2" */
    0x7d, 0x8f, 0x18, 0x30, 0xc3, 0x0c, 0x30, 0xc1, 0xfc,
    /* U+0033 "3" */
    0x7d, 0x8f, 0x18, 0x33, 0xc0, 0xc1, 0xe3, 0xc6, 0xf8,
    /* U+0034 "4" */
    0x06, 0x1c, 0x79, 0xb6, 0x78, 0xff, 0x83, 0x06, 0x0c,
    /* U+0035 "5" */
    0xff, 0x83, 0x06, 0x0f, 0xc0, 0xc1, 0x83, 0xc6, 0xf8,
    /* U+0036 "6" */
    0x3c, 0xc3, 0x06, 0x0f, 0xd8, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0037 "7" */
    0xfe, 0x0c, 0x18, 0x60, 0xc3, 0x06, 0x18, 0x30, 0x60,
    /* U+0038 "8" */
    0x7d, 0x8f, 0x1e, 0x37, 0xd8, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0039 "9" */
    0x7d, 0x8f, 0x1e, 0x3c, 0x6f, 0xc1, 0x83, 0x0c, 0xf0,
    /* U+003A ":" */
    0xf0, 0x3c,
    /* U+003B ";" */
    0x6c, 0x00, 0xde,
    /* U+003C "<" */
    0x0c, 0x63, 0x18, 0xc1, 0x83, 0x06, 0x0c,
    /* U+003D "=" */
    0xfe, 0x00, 0x07, 0xf0,
    /* U+003E ">" */
    0xc1, 0x83, 0x06, 0x0c, 0x63, 0x18, 0xc0,
    /* U+003F "?" */
    0x7d, 0x8f, 0x1e, 0x30, 0xc3, 0x06, 0x00, 0x18, 0x30,
    /* U+0040 "@" */
    0x7d, 0x8f, 0x3e, 0xbd, 0x7a, 0xf5, 0xe7, 0xc0, 0xfc,
    /* U+0041 "A" */
    0x7d, 0x8f, 0x1e, 0x3c, 0x7f, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0042 "B" */
    0xfd, 0x8f, 0x1e, 0x3f, 0xd8, 0xf1, 0xe3, 0xc7, 0xf8,
    /* U+0043 "C" */
    0x7d, 0x8f, 0x1e, 0x0c, 0x18, 0x30, 0x63, 0xc6, 0xf8,
    /* U+0044 "D" */
    0xf9, 0x9b, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xcd, 0xf0,
    /* U+0045 "E" */
    0xff, 0x83, 0x06, 0x0f, 0x98, 0x30, 0x60, 0xc1, 0xfc,
    /* U+0046 "F" */
    0xff, 0x83, 0x06, 0x0f, 0x98, 0x30, 0x60, 0xc1, 0x80,
    /* U+0047 "G" */
    0x7d, 0x8f, 0x1e, 0x0c, 0x1b, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0048 "H" */
    0xc7, 0x8f, 0x1e, 0x3f, 0xf8, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0049 "I" */
    0xf6, 0x66, 0x66, 0x66, 0x6f,
    /* U+004A "J" */
    0x1e, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x66, 0xcc, 0xf0,
    /* U+004B "K" */
    0xc7, 0x8f, 0x36, 0xcf, 0x1e, 0x36, 0x66, 0xc7, 0x8c,
    /* U+004C "L" */
    0xc1, 0x83, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc1, 0xfc,
    /* U+004D "M" */
    0x83, 0x8f, 0xbf, 0xfd, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+004E "N" */
    0xc7, 0x8f, 0x1f, 0x3f, 0x7b, 0xf3, 0xe3, 0xc7, 0x8c,
    /* U+004F "O" */
    0x7d, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0050 "P" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x7f, 0xb0, 0x60, 0xc1, 0x80,
    /* U+0051 "Q" */
    0x7d, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xde, 0xf8, 0x18,
    /* U+0052 "R" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x7f, 0xbc, 0x6c, 0xcd, 0x8c,
    /* U+0053 "S" */
    0x7d, 0x8f, 0x06, 0x07, 0xc0, 0xc1, 0xe3, 0xc6, 0xf8,
    /* U+0054 "T" */
    0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+0055 "U" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0056 "V" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x6d, 0x9b, 0x36, 0x38, 0x70,
    /* U+0057 "W" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x7a, 0xff, 0xf7, 0xc7, 0x04,
    /* U+0058 "X" */
    0xc7, 0x8d, 0xb3, 0x63, 0x87, 0x1b, 0x36, 0xc7, 0x8c,
    /* U+0059 "Y" */
    0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+005A "Z" */
    0xfe, 0x0c, 0x18, 0x61, 0x86, 0x18, 0x60, 0xc1, 0xfc,
    /* U+005B "[" */
    0xfc, 0xcc, 0xcc, 0xcc, 0xcf,
    /* U+005C "\\" */
    0xc3, 0x06, 0x18, 0x30, 0xc1, 0x86, 0x0c, 0x30,
    /* U+005D "]" */
    0xf3, 0x33, 0x33, 0x33, 0x3f,
    /* U+005E "^" */
    0x31, 0xec, 0xc0,
    /* U+005F "_" */
    0xfe,
    /* U+0060 "`" */
    0xcc,
    /* U+0061 "a" */
    0x7c, 0x0d, 0xfe, 0x3c, 0x78, 0xdf, 0x80,
    /* U+0062 "b" */
    0xc1, 0x83, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0xf8,
    /* U+0063 "c" */
    0x7d, 0x8f, 0x06, 0x0c, 0x18, 0xdf, 0x00,
    /* U+0064 "d" */
    0x06, 0x0c, 0x1b, 0xfc, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+0065 "e" */
    0x7d, 0x8f, 0x1f, 0xfc, 0x18, 0x1f, 0x00,
    /* U+0066 "f" */
    0x1e, 0x60, 0xc7, 0xe3, 0x06, 0x0c, 0x18, 0x30, 0x60,
    /* U+0067 "g" */
    0x7f, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x83, 0x7c,
    /* U+0068 "h" */
    0xc1, 0x83, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0069 "i" */
    0x66, 0x0e, 0x66, 0x66, 0x6f,
    /* U+006A "j" */
    0x0c, 0x30, 0x07, 0x0c, 0x30, 0xc3, 0x0f, 0x3c, 0xde,
    /* U+006B "k" */
    0xc1, 0x83, 0x06, 0x3c, 0xdb, 0x3c, 0x6c, 0xcd, 0x8c,
    /* U+006C "l" */
    0xe6, 0x66, 0x66, 0x66, 0x6f,
    /* U+006D "m" */
    0xfd, 0xaf, 0x5e, 0xbd, 0x7a, 0xf5, 0x80,
    /* U+006E "n" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0x80,
    /* U+006F "o" */
    0x7d, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x00,
    /* U+0070 "p" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x78, 0xff, 0x60, 0xc0,
    /* U+0071 "q" */
    0x7f, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x83, 0x06,
    /* U+0072 "r" */
    0xdf, 0xe3, 0x86, 0x0c, 0x18, 0x30, 0x00,
    /* U+0073 "s" */
    0x7f, 0x83, 0x03, 0xe0, 0x60, 0xff, 0x00,
    /* U+0074 "t" */
    0x30, 0x60, 0xc7, 0xe3, 0x06, 0x0c, 0x18, 0x30, 0x3c,
    /* U+0075 "u" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x80,
    /* U+0076 "v" */
    0xc7, 0x8f, 0x1b, 0x66, 0xc7, 0x0e, 0x00,
    /* U+0077 "w" */
    0xc7, 0x8f, 0x5e, 0xbd, 0x7a, 0xdf, 0x00,
    /* U+0078 "x" */
    0xc7, 0x8d, 0xb1, 0xc6, 0xd8, 0xf1, 0x80,
    /* U+0079 "y" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x78, 0xdf, 0x83, 0x7c,
    /* U+007A "z" */
    0xfe, 0x18, 0x61, 0x86, 0x18, 0x3f, 0x80,
    /* U+007B "{" */
    0x3b, 0x18, 0xcc, 0x31, 0x8c, 0x61, 0xc0,
    /* U+007C "|" */
    0xff, 0xff, 0xf0,
    /* U+007D "}" */
    0xe1, 0x8c, 0x61, 0x98, 0xc6, 0x37, 0x00,
    /* U+007E "~" */
    0x73, 0xdb, 0xce,
    /* U+00A0 " " */
    /* U+00A1 "¡" */
    0xf3, 0xff, 0xf0,
    /* U+00A2 "¢" */
    0x10, 0x21, 0xf6, 0xbd, 0x1a, 0x34, 0x6b, 0x7c, 0x20, 0x40,
    /* U+00A3 "£" */
    0x38, 0xd9, 0x83, 0x0f, 0x8c, 0x18, 0x30, 0x67, 0xfc,
    /* U+00A4 "¤" */
    0xcd, 0xec, 0xf3, 0xcd, 0xec, 0xc0,
    /* U+00A5 "¥" */
    0xc3, 0xc3, 0x66, 0x3c, 0x18, 0x7e, 0x18, 0x7e, 0x18, 0x18,
    /* U+00A6 "¦" */
    0xff, 0x0f, 0xf0,
    /* U+00A7 "§" */
    0x7b, 0x3c, 0x1c, 0xdb, 0x3c, 0xdb, 0x38, 0x3c, 0xde,
    /* U+00A8 "¨" */
    0xde, 0xc0,
    /* U+00A9 "©" */
    0x7e, 0x81, 0x99, 0xa5, 0xa1, 0xa5, 0x99, 0x81, 0x7e,
    /* U+00AA "ª" */
    0x78, 0x37, 0xf3, 0x7c, 0x0f, 0xc0,
    /* U+00AB "«" */
    0x1b, 0x36, 0x6c, 0xd8, 0x6c, 0x36, 0x1b,
    /* U+00AC "¬" */
    0xfe, 0x0c, 0x18, 0x30,
    /* U+00AD "­" */
    0xf8,
    /* U+00AE "®" */
    0x7e, 0x81, 0xb9, 0xa5, 0xb9, 0xa9, 0xa5, 0x81, 0x7e,
    /* U+00AF "¯" */
    0xf8,
    /* U+00B0 "°" */
    0x76, 0xf6, 0xe0,
    /* U+00B1 "±" */
    0x30, 0xcf, 0xcc, 0x30, 0x0f, 0xc0,
    /* U+00B2 "²" */
    0x76, 0xc6, 0x66, 0x7c,
    /* U+00B3 "³" */
    0xf0, 0xdc, 0x31, 0xf8,
    /* U+00B4 "´" */
    0x78,
    /* U+00B5 "µ" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x79, 0xfd, 0xe0, 0xc0,
    /* U+00B6 "¶" */
    0x7f, 0xaf, 0x5e, 0xbd, 0x6e, 0xc5, 0x8b, 0x16, 0x2c,
    /* U+00B7 "·" */
    0xf0,
    /* U+00B8 "¸" */
    0x6f, 0x00,
    /* U+00B9 "¹" */
    0x6e, 0x66, 0x6f,
    /* U+00BA "º" */
    0x7b, 0x3c, 0xf3, 0x78, 0x0f, 0xc0,
    /* U+00BB "»" */
    0xd8, 0x6c, 0x36, 0x1b, 0x36, 0x6c, 0xd8,
    /* U+00BC "¼" */
    0x61, 0xc1, 0x8b, 0x36, 0xc3, 0x0c, 0x33, 0xcf, 0x34, 0xf8, 0x30, 0x60,
    /* U+00BD "½" */
    0x61, 0xc1, 0x8b, 0x36, 0xc3, 0x0c, 0x30, 0xdd, 0x6c, 0x30, 0xc3, 0xe0,
    /* U+00BE "¾" */
    0xe0, 0x61, 0x89, 0xbe, 0xc3, 0x0c, 0x33, 0xcf, 0x34, 0xf8, 0x30, 0x60,
    /* U+00BF "¿" */
    0x30, 0x60, 0x01, 0x83, 0x0c, 0x31, 0xe3, 0xc6, 0xf8,
    /* U+00C0 "À" */
    0x30, 0x30, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C1 "Á" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C2 "Â" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C3 "Ã" */
    0x77, 0xb8, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C4 "Ä" */
    0x6c, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C5 "Å" */
    0x38, 0xd8, 0xe3, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+00C6 "Æ" */
    0x7f, 0xb3, 0x66, 0xcf, 0xfb, 0x36, 0x6c, 0xd9, 0xbc,
    /* U+00C7 "Ç" */
    0x7d, 0x8f, 0x1e, 0x0c, 0x18, 0x30, 0x63, 0xc6, 0xf8, 0xc3, 0x00,
    /* U+00C8 "È" */
    0x30, 0x30, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+00C9 "É" */
    0x18, 0x60, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+00CA "Ê" */
    0x38, 0xd8, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+00CB "Ë" */
    0x6c, 0xd8, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+00CC "Ì" */
    0xc6, 0x0f, 0x66, 0x66, 0x66, 0x6f,
    /* U+00CD "Í" */
    0x36, 0x0f, 0x66, 0x66, 0x66, 0x6f,
    /* U+00CE "Î" */
    0x76, 0xc0, 0xf3, 0x18, 0xc6, 0x31, 0x8c, 0xf0,
    /* U+00CF "Ï" */
    0xcf, 0x30, 0x1e, 0x30, 0xc3, 0x0c, 0x30, 0xc3, 0x1e,
    /* U+00D0 "Ð" */
    0x78, 0xd9, 0x9b, 0x3f, 0x6c, 0xd9, 0xb3, 0x6c, 0xf0,
    /* U+00D1 "Ñ" */
    0x77, 0xb8, 0x06, 0x3c, 0x7c, 0xfd, 0xef, 0xcf, 0x8f, 0x1e, 0x30,
    /* U+00D2 "Ò" */
    0x30, 0x30, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00D3 "Ó" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00D4 "Ô" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00D5 "Õ" */
    0x77, 0xb8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00D6 "Ö" */
    0x6c, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00D7 "×" */
    0xc6, 0xd8, 0xe1, 0xc6, 0xd8, 0xc0,
    /* U+00D8 "Ø" */
    0x7c, 0xc7, 0xc6, 0xce, 0xde, 0xf6, 0xe6, 0xc6, 0xc6, 0x7c,
    /* U+00D9 "Ù" */
    0x30, 0x33, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00DA "Ú" */
    0x18, 0x63, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00DB "Û" */
    0x38, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00DC "Ü" */
    0x6c, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+00DD "Ý" */
    0x0c, 0x18, 0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+00DE "Þ" */
    0xc1, 0x83, 0xf6, 0x3c, 0x78, 0xf1, 0xfe, 0xc1, 0x80,
    /* U+00DF "ß" */
    0x79, 0x9b, 0x36, 0x4f, 0xd8, 0xf1, 0xe3, 0xe7, 0xb8,
    /* U+00E0 "à" */
    0x30, 0x30, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E1 "á" */
    0x18, 0x60, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E2 "â" */
    0x38, 0xd8, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E3 "ã" */
    0x77, 0xb8, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E4 "ä" */
    0x6c, 0xd8, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E5 "å" */
    0x38, 0xd8, 0xe3, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00E6 "æ" */
    0x6c, 0x2c, 0x5b, 0xfd, 0x1a, 0x1b, 0x00,
    /* U+00E7 "ç" */
    0x7d, 0x8f, 0x06, 0x0c, 0x18, 0xdf, 0x18, 0x60,
    /* U+00E8 "è" */
    0x30, 0x30, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+00E9 "é" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+00EA "ê" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+00EB "ë" */
    0x6c, 0xd8, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+00EC "ì" */
    0xc6, 0x0e, 0x66, 0x66, 0x6f,
    /* U+00ED "í" */
    0x36, 0x0e, 0x66, 0x66, 0x6f,
    /* U+00EE "î" */
    0x76, 0xc0, 0xe3, 0x18, 0xc6, 0x33, 0xc0,
    /* U+00EF "ï" */
    0xde, 0xc0, 0xe3, 0x18, 0xc6, 0x33, 0xc0,
    /* U+00F0 "ð" */
    0x68, 0x61, 0x63, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F1 "ñ" */
    0x77, 0xb8, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+00F2 "ò" */
    0x30, 0x30, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F3 "ó" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F4 "ô" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F5 "õ" */
    0x77, 0xb8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F6 "ö" */
    0x6c, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+00F7 "÷" */
    0x30, 0xc0, 0x3f, 0x00, 0xc3, 0x00,
    /* U+00F8 "ø" */
    0x3d, 0x67, 0x6e, 0x7e, 0x76, 0xe6, 0xbc,
    /* U+00F9 "ù" */
    0x30, 0x30, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00FA "ú" */
    0x18, 0x60, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00FB "û" */
    0x38, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00FC "ü" */
    0x6c, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+00FD "ý" */
    0x18, 0x60, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+00FE "þ" */
    0xc1, 0x83, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0xfb, 0x06, 0x00,
    /* U+00FF "ÿ" */
    0x6c, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+0100 "Ā" */
    0x7c, 0x01, 0xf6, 0x3c, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+0101 "ā" */
    0x7c, 0x01, 0xf0, 0x37, 0xf8, 0xf1, 0xe3, 0x7e,
    /* U+0102 "Ă" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+0103 "ă" */
    0x6c, 0x70, 0x03, 0xe0, 0x6f, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+0104 "Ą" */
    0x7c, 0xc6, 0xc6, 0xc6, 0xc6, 0xfe, 0xc6, 0xc6, 0xc6, 0xc6, 0x0c, 0x07,
    /* U+0105 "ą" */
    0x7c, 0x06, 0x7e, 0xc6, 0xc6, 0xc6, 0x7e, 0x0c, 0x07,
    /* U+0106 "Ć" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0xf0, 0x60, 0xc1, 0x8f, 0x1b, 0xe0,
    /* U+0107 "ć" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0x30, 0x60, 0xc6, 0xf8,
    /* U+0108 "Ĉ" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0xf0, 0x60, 0xc1, 0x8f, 0x1b, 0xe0,
    /* U+0109 "ĉ" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0x30, 0x60, 0xc6, 0xf8,
    /* U+010A "Ċ" */
    0x18, 0x30, 0x03, 0xec, 0x78, 0xf0, 0x60, 0xc1, 0x8f, 0x1b, 0xe0,
    /* U+010B "ċ" */
    0x18, 0x30, 0x03, 0xec, 0x78, 0x30, 0x60, 0xc6, 0xf8,
    /* U+010C "Č" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xf0, 0x60, 0xc1, 0x8f, 0x1b, 0xe0,
    /* U+010D "č" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0x30, 0x60, 0xc6, 0xf8,
    /* U+010E "Ď" */
    0x6c, 0x70, 0x07, 0xcc, 0xd8, 0xf1, 0xe3, 0xc7, 0x8f, 0x37, 0xc0,
    /* U+010F "ď" */
    0x6c, 0x70, 0x18, 0x30, 0x6f, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xf0,
    /* U+0110 "Đ" */
    0x78, 0xd9, 0x9b, 0x3f, 0x6c, 0xd9, 0xb3, 0x6c, 0xf0,
    /* U+0111 "đ" */
    0x06, 0x1f, 0x06, 0x7e, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0x7e,
    /* U+0112 "Ē" */
    0x7c, 0x03, 0xfe, 0x0c, 0x18, 0x3e, 0x60, 0xc1, 0x83, 0x07, 0xf0,
    /* U+0113 "ē" */
    0x7c, 0x01, 0xf6, 0x3c, 0x7f, 0xf0, 0x60, 0x7c,
    /* U+0114 "Ĕ" */
    0x6c, 0x70, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+0115 "ĕ" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+0116 "Ė" */
    0x18, 0x30, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+0117 "ė" */
    0x18, 0x30, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+0118 "Ę" */
    0xfe, 0xc0, 0xc0, 0xc0, 0xf8, 0xc0, 0xc0, 0xc0, 0xc0, 0xfe, 0x0c, 0x07,
    /* U+0119 "ę" */
    0x7d, 0x8f, 0x1f, 0xfc, 0x18, 0x1f, 0x0c, 0x0e,
    /* U+011A "Ě" */
    0x6c, 0x70, 0x07, 0xfc, 0x18, 0x30, 0x7c, 0xc1, 0x83, 0x07, 0xf0,
    /* U+011B "ě" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xff, 0xe0, 0xc0, 0xf8,
    /* U+011C "Ĝ" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0x30, 0x6f, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+011D "ĝ" */
    0x38, 0xd8, 0x03, 0xfc, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+011E "Ğ" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0x30, 0x6f, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+011F "ğ" */
    0x6c, 0x70, 0x03, 0xfc, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+0120 "Ġ" */
    0x18, 0x30, 0x03, 0xec, 0x78, 0x30, 0x6f, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+0121 "ġ" */
    0x18, 0x30, 0x03, 0xfc, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+0122 "Ģ" */
    0x7d, 0x8f, 0x1e, 0x0c, 0x1b, 0xf1, 0xe3, 0xc6, 0xf8, 0xc3, 0x00,
    /* U+0123 "ģ" */
    0x0c, 0x30, 0x60, 0x07, 0xf8, 0xf1, 0xe3, 0xc7, 0x8d, 0xf8, 0x37, 0xc0,
    /* U+0124 "Ĥ" */
    0x38, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xff, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+0125 "ĥ" */
    0x1c, 0x6f, 0x06, 0x0c, 0x1f, 0xb1, 0xe3, 0xc7, 0x8f, 0x1e, 0x30,
    /* U+0126 "Ħ" */
    0x66, 0xff, 0x66, 0x66, 0x7e, 0x66, 0x66, 0x66, 0x66, 0x66,
    /* U+0127 "ħ" */
    0x61, 0xf1, 0x83, 0xe6, 0x6c, 0xd9, 0xb3, 0x66, 0xcc,
    /* U+0128 "Ĩ" */
    0x77, 0xb8, 0x01, 0xe1, 0x83, 0x06, 0x0c, 0x18, 0x30, 0x61, 0xe0,
    /* U+0129 "ĩ" */
    0x77, 0xb8, 0x01, 0xc1, 0x83, 0x06, 0x0c, 0x18, 0x78,
    /* U+012A "Ī" */
    0xfc, 0x07, 0x8c, 0x30, 0xc3, 0x0c, 0x30, 0xc3, 0x1e,
    /* U+012B "ī" */
    0xf8, 0x1c, 0x63, 0x18, 0xc6, 0x78,
    /* U+012C "Ĭ" */
    0xdb, 0x80, 0xf3, 0x18, 0xc6, 0x31, 0x8c, 0xf0,
    /* U+012D "ĭ" */
    0xdb, 0x80, 0xe3, 0x18, 0xc6, 0x33, 0xc0,
    /* U+012E "Į" */
    0xf3, 0x18, 0xc6, 0x31, 0x8c, 0x67, 0x98, 0x70,
    /* U+012F "į" */
    0x63, 0x01, 0xc6, 0x31, 0x8c, 0x67, 0x98, 0x70,
    /* U+0130 "İ" */
    0x66, 0x0f, 0x66, 0x66, 0x66, 0x6f,
    /* U+0131 "ı" */
    0xe6, 0x66, 0x66, 0xf0,
    /* U+0132 "Ĳ" */
    0xcf, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xf6, 0xf6, 0xdc,
    /* U+0133 "ĳ" */
    0xc7, 0x8c, 0x06, 0x7c, 0x78, 0xf1, 0xe3, 0xc7, 0xec, 0xd8, 0xe0,
    /* U+0134 "Ĵ" */
    0x1c, 0x6c, 0x00, 0xf0, 0xc1, 0x83, 0x06, 0x0d, 0x9b, 0x33, 0xc0,
    /* U+0135 "ĵ" */
    0x1c, 0x6c, 0x00, 0xe0, 0xc1, 0x83, 0x06, 0x0d, 0x9b, 0x33, 0xc0,
    /* U+0136 "Ķ" */
    0xc7, 0x8f, 0x36, 0xcf, 0x1e, 0x36, 0x66, 0xc7, 0xec, 0xc3, 0x00,
    /* U+0137 "ķ" */
    0xc1, 0x83, 0x06, 0x3c, 0xdb, 0x3c, 0x6c, 0xcd, 0xec, 0xc3, 0x00,
    /* U+0138 "ĸ" */
    0xc7, 0x9b, 0x67, 0x8d, 0x99, 0xb1, 0x80,
    /* U+0139 "Ĺ" */
    0x61, 0x80, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x07, 0xf0,
    /* U+013A "ĺ" */
    0x36, 0x0e, 0x66, 0x66, 0x66, 0x6f,
    /* U+013B "Ļ" */
    0xc1, 0x83, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc1, 0xfc, 0xc3, 0x00,
    /* U+013C "ļ" */
    0xe6, 0x66, 0x66, 0x66, 0x6f, 0x6c,
    /* U+013D "Ľ" */
    0x6c, 0x73, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc1, 0x83, 0x07, 0xf0,
    /* U+013E "ľ" */
    0xdb, 0x80, 0xe3, 0x18, 0xc6, 0x31, 0x8c, 0xf0,
    /* U+013F "Ŀ" */
    0xc1, 0x83, 0x06, 0x0c, 0xd9, 0xb0, 0x60, 0xc1, 0xfc,
    /* U+0140 "ŀ" */
    0xe1, 0x86, 0x18, 0x6d, 0xb6, 0x18, 0x63, 0xc0,
    /* U+0141 "Ł" */
    0x60, 0x60, 0x60, 0x60, 0x70, 0xe0, 0x60, 0x60, 0x60, 0x7f,
    /* U+0142 "ł" */
    0xe6, 0x66, 0x7e, 0x66, 0x6f,
    /* U+0143 "Ń" */
    0x18, 0x63, 0x1e, 0x3c, 0x7c, 0xfd, 0xef, 0xcf, 0x8f, 0x1e, 0x30,
    /* U+0144 "ń" */
    0x18, 0x60, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0145 "Ņ" */
    0xc7, 0x8f, 0x1f, 0x3f, 0x7b, 0xf3, 0xe3, 0xc7, 0xec, 0xc3, 0x00,
    /* U+0146 "ņ" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x78, 0xfd, 0x98, 0x60,
    /* U+0147 "Ň" */
    0x6c, 0x73, 0x1e, 0x3c, 0x7c, 0xfd, 0xef, 0xcf, 0x8f, 0x1e, 0x30,
    /* U+0148 "ň" */
    0x6c, 0x70, 0x07, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8c,
    /* U+0149 "ŉ" */
    0x60, 0xc3, 0x00, 0x0f, 0xd8, 0xf1, 0xe3, 0xc7, 0x8f, 0x18,
    /* U+014A "Ŋ" */
    0xc7, 0x8f, 0x1f, 0x3f, 0x7b, 0xf3, 0xe3, 0xc7, 0x8c, 0x18, 0xe0,
    /* U+014B "ŋ" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0x83, 0x1c,
    /* U+014C "Ō" */
    0x7c, 0x01, 0xf6, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+014D "ō" */
    0x7c, 0x01, 0xf6, 0x3c, 0x78, 0xf1, 0xe3, 0x7c,
    /* U+014E "Ŏ" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+014F "ŏ" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0150 "Ő" */
    0x36, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+0151 "ő" */
    0x36, 0xd8, 0x03, 0xec, 0x78, 0xf1, 0xe3, 0xc6, 0xf8,
    /* U+0152 "Œ" */
    0x7f, 0xb3, 0x66, 0xcd, 0xfb, 0x36, 0x6c, 0xd8, 0xfc,
    /* U+0153 "œ" */
    0x7d, 0xaf, 0x5e, 0xfd, 0x1a, 0x1f, 0x00,
    /* U+0154 "Ŕ" */
    0x18, 0x60, 0x07, 0xec, 0x78, 0xf1, 0xfe, 0xf1, 0xb3, 0x36, 0x30,
    /* U+0155 "ŕ" */
    0x18, 0x60, 0x06, 0xff, 0x1c, 0x30, 0x60, 0xc1, 0x80,
    /* U+0156 "Ŗ" */
    0xfd, 0x8f, 0x1e, 0x3c, 0x7f, 0xbc, 0x6c, 0xcd, 0xec, 0xc3, 0x00,
    /* U+0157 "ŗ" */
    0xdf, 0xe3, 0x86, 0x0c, 0x18, 0x38, 0x30, 0xc0,
    /* U+0158 "Ř" */
    0x6c, 0x70, 0x07, 0xec, 0x78, 0xf1, 0xfe, 0xf1, 0xb3, 0x36, 0x30,
    /* U+0159 "ř" */
    0x6c, 0x70, 0x06, 0xff, 0x1c, 0x30, 0x60, 0xc1, 0x80,
    /* U+015A "Ś" */
    0x18, 0x60, 0x03, 0xec, 0x78, 0x30, 0x3e, 0x06, 0x0f, 0x1b, 0xe0,
    /* U+015B "ś" */
    0x0c, 0x30, 0x03, 0xfc, 0x18, 0x1f, 0x03, 0x07, 0xf8,
    /* U+015C "Ŝ" */
    0x38, 0xd8, 0x03, 0xec, 0x78, 0x30, 0x3e, 0x06, 0x0f, 0x1b, 0xe0,
    /* U+015D "ŝ" */
    0x38, 0xd8, 0x03, 0xfc, 0x18, 0x1f, 0x03, 0x07, 0xf8,
    /* U+015E "Ş" */
    0x7d, 0x8f, 0x06, 0x07, 0xc0, 0xc1, 0xe3, 0xc6, 0xf8, 0xc3, 0x00,
    /* U+015F "ş" */
    0x7f, 0x83, 0x03, 0xe0, 0x60, 0xff, 0x18, 0x60,
    /* U+0160 "Š" */
    0x6c, 0x70, 0x03, 0xec, 0x78, 0x30, 0x3e, 0x06, 0x0f, 0x1b, 0xe0,
    /* U+0161 "š" */
    0x6c, 0x70, 0x03, 0xfc, 0x18, 0x1f, 0x03, 0x07, 0xf8,
    /* U+0162 "Ţ" */
    0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x1c, 0x0c, 0x18,
    /* U+0163 "ţ" */
    0x30, 0x60, 0xc7, 0xe3, 0x06, 0x0c, 0x18, 0x30, 0x3c, 0x30, 0xc0,
    /* U+0164 "Ť" */
    0x6c, 0x38, 0x00, 0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+0165 "ť" */
    0x6c, 0x70, 0x01, 0x83, 0x1f, 0x8c, 0x18, 0x30, 0x60, 0xc0, 0xf0,
    /* U+0166 "Ŧ" */
    0xff, 0x18, 0x18, 0x18, 0x7e, 0x18, 0x18, 0x18, 0x18, 0x18,
    /* U+0167 "ŧ" */
    0x30, 0x60, 0xc7, 0xe3, 0x0f, 0x0c, 0x18, 0x30, 0x3c,
    /* U+0168 "Ũ" */
    0x77, 0xb8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+0169 "ũ" */
    0x77, 0xb8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+016A "Ū" */
    0x7c, 0x03, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+016B "ū" */
    0x7c, 0x03, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0x7e,
    /* U+016C "Ŭ" */
    0x6c, 0x73, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+016D "ŭ" */
    0x6c, 0x70, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+016E "Ů" */
    0x38, 0xd8, 0xe6, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+016F "ů" */
    0x38, 0xd8, 0xe6, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+0170 "Ű" */
    0x36, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc7, 0x8f, 0x1b, 0xe0,
    /* U+0171 "ű" */
    0x36, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc,
    /* U+0172 "Ų" */
    0xc7, 0x8f, 0x1e, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xf8, 0x60, 0x70,
    /* U+0173 "ų" */
    0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0xc6, 0x7e, 0x0c, 0x07,
    /* U+0174 "Ŵ" */
    0x38, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xeb, 0xff, 0xdf, 0x1c, 0x10,
    /* U+0175 "ŵ" */
    0x38, 0xd8, 0x06, 0x3c, 0x7a, 0xf5, 0xeb, 0xd6, 0xf8,
    /* U+0176 "Ŷ" */
    0x38, 0x6c, 0x00, 0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18,
    /* U+0177 "ŷ" */
    0x38, 0xd8, 0x06, 0x3c, 0x78, 0xf1, 0xe3, 0xc6, 0xfc, 0x1b, 0xe0,
    /* U+0178 "Ÿ" */
    0x66, 0x66, 0x00, 0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18, 0x18,
    /* U+0179 "Ź" */
    0x18, 0x60, 0x07, 0xf0, 0x61, 0x86, 0x18, 0x61, 0x83, 0x07, 0xf0,
    /* U+017A "ź" */
    0x18, 0x60, 0x07, 0xf0, 0xc3, 0x0c, 0x30, 0xc1, 0xfc,
    /* U+017B "Ż" */
    0x18, 0x30, 0x07, 0xf0, 0x61, 0x86, 0x18, 0x61, 0x83, 0x07, 0xf0,
    /* U+017C "ż" */
    0x18, 0x30, 0x07, 0xf0, 0xc3, 0x0c, 0x30, 0xc1, 0xfc,
    /* U+017D "Ž" */
    0x6c, 0x70, 0x07, 0xf0, 0x61, 0x86, 0x18, 0x61, 0x83, 0x07, 0xf0,
    /* U+017E "ž" */
    0x6c, 0x70, 0x07, 0xf0, 0xc3, 0x0c, 0x30, 0xc1, 0xfc,
    /* U+017F "ſ" */
    0x7e, 0x31, 0x8c, 0x63, 0x18, 0xc6, 0x00,
    /* U+0218 "Ș" */
    0x7d, 0x8f, 0x06, 0x07, 0xc0, 0xc1, 0xe3, 0xc6, 0xf8, 0xc3, 0x00,
    /* U+0219 "ș" */
    0x7f, 0x83, 0x03, 0xe0, 0x60, 0xff, 0x18, 0x60,
    /* U+021A "Ț" */
    0xff, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x1c, 0x0c, 0x18,
    /* U+021B "ț" */
    0x30, 0x60, 0xc7, 0xe3, 0x06, 0x0c, 0x18, 0x30, 0x3c, 0x18, 0x60,
    /* U+2022 "•" */
    0x6f, 0xf6,
    /* U+20AC "€" */
    0x1e, 0x33, 0x60, 0xfc, 0x60, 0xfc, 0x60, 0x33, 0x1e,
    0x00 /* keeps the array non-empty */
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 128, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 128, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 3, .adv_w = 128, .box_w = 6, .box_h = 3, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 6, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 15, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 27, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 37, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 46, .adv_w = 128, .box_w = 2, .box_h = 3, .ofs_x = 3, .ofs_y = 8},
    {.bitmap_index = 47, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 52, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 57, .adv_w = 128, .box_w = 7, .box_h = 5, .ofs_x = 0, .ofs_y = 2},
    {.bitmap_index = 62, .adv_w = 128, .box_w = 6, .box_h = 5, .ofs_x = 1, .ofs_y = 2},
    {.bitmap_index = 66, .adv_w = 128, .box_w = 3, .box_h = 3, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 68, .adv_w = 128, .box_w = 7, .box_h = 1, .ofs_x = 0, .ofs_y = 4},
    {.bitmap_index = 69, .adv_w = 128, .box_w = 2, .box_h = 2, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 70, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 78, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 87, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 95, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 104, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 113, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 122, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 131, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 140, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 149, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 158, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 167, .adv_w = 128, .box_w = 2, .box_h = 7, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 169, .adv_w = 128, .box_w = 3, .box_h = 8, .ofs_x = 2, .ofs_y = -1},
    {.bitmap_index = 172, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 179, .adv_w = 128, .box_w = 7, .box_h = 4, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 183, .adv_w = 128, .box_w = 6, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 190, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 199, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 208, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 217, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 226, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 235, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 244, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 253, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 262, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 271, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 280, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 285, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 294, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 303, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 312, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 321, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 330, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 339, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 348, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 358, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 367, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 376, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 386, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 395, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 404, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 413, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 422, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 432, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 441, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 446, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 454, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 459, .adv_w = 128, .box_w = 6, .box_h = 3, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 462, .adv_w = 128, .box_w = 7, .box_h = 1, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 463, .adv_w = 128, .box_w = 3, .box_h = 2, .ofs_x = 2, .ofs_y = 10},
    {.bitmap_index = 464, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 471, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 480, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 487, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 496, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 503, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 512, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 520, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 529, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 534, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 543, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 552, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 557, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 564, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 571, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 578, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 586, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 594, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 601, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 608, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 617, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 624, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 631, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 638, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 645, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 653, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 660, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 667, .adv_w = 128, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 670, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 677, .adv_w = 128, .box_w = 8, .box_h = 3, .ofs_x = 0, .ofs_y = 8},
    {.bitmap_index = 680, .adv_w = 128, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 680, .adv_w = 128, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 683, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 693, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 702, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 708, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 718, .adv_w = 128, .box_w = 2, .box_h = 10, .ofs_x = 3, .ofs_y = 0},
    {.bitmap_index = 721, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 730, .adv_w = 128, .box_w = 5, .box_h = 2, .ofs_x = 1, .ofs_y = 10},
    {.bitmap_index = 732, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 741, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 747, .adv_w = 128, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 754, .adv_w = 128, .box_w = 7, .box_h = 4, .ofs_x = 0, .ofs_y = 3},
    {.bitmap_index = 758, .adv_w = 128, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 759, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 768, .adv_w = 128, .box_w = 5, .box_h = 1, .ofs_x = 1, .ofs_y = 11},
    {.bitmap_index = 769, .adv_w = 128, .box_w = 5, .box_h = 4, .ofs_x = 1, .ofs_y = 7},
    {.bitmap_index = 772, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 778, .adv_w = 128, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 5},
    {.bitmap_index = 782, .adv_w = 128, .box_w = 5, .box_h = 6, .ofs_x = 1, .ofs_y = 5},
    {.bitmap_index = 786, .adv_w = 128, .box_w = 3, .box_h = 2, .ofs_x = 2, .ofs_y = 10},
    {.bitmap_index = 787, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 795, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 804, .adv_w = 128, .box_w = 2, .box_h = 2, .ofs_x = 3, .ofs_y = 4},
    {.bitmap_index = 805, .adv_w = 128, .box_w = 3, .box_h = 3, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 807, .adv_w = 128, .box_w = 4, .box_h = 6, .ofs_x = 2, .ofs_y = 5},
    {.bitmap_index = 810, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 816, .adv_w = 128, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 823, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 835, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 847, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 859, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 868, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 879, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 890, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 901, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 912, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 923, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 934, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 943, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 954, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 965, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 976, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 987, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 998, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1004, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1010, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1018, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1027, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1036, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1047, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1058, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1069, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1080, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1091, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1102, .adv_w = 128, .box_w = 7, .box_h = 6, .ofs_x = 0, .ofs_y = 1},
    {.bitmap_index = 1108, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1118, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1129, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1140, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1151, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1162, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1174, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1183, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1192, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1201, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1210, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1219, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1228, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1237, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1246, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1253, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1261, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1270, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1279, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1288, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1297, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1302, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1307, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1314, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1321, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1330, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1339, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1348, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1357, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1366, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1375, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1384, .adv_w = 128, .box_w = 6, .box_h = 7, .ofs_x = 1, .ofs_y = 1},
    {.bitmap_index = 1390, .adv_w = 128, .box_w = 8, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1397, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1406, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1415, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1424, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1433, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1444, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1455, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1466, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1477, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1485, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1496, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1505, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1517, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1526, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1537, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1546, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1557, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1566, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1577, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1586, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1597, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1606, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1617, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1628, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1637, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1647, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1658, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1666, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1677, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1686, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1697, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1706, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1718, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1726, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1737, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1746, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1757, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1768, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1779, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1790, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1801, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1812, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1823, .adv_w = 128, .box_w = 7, .box_h = 13, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1835, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1846, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1857, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1867, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1876, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1887, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1896, .adv_w = 128, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1905, .adv_w = 128, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1911, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1919, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 1926, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -2},
    {.bitmap_index = 1934, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 2, .ofs_y = -2},
    {.bitmap_index = 1942, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1948, .adv_w = 128, .box_w = 4, .box_h = 7, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 1952, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1962, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 1973, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 1984, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1995, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2006, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2017, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2024, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2035, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2041, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2052, .adv_w = 128, .box_w = 4, .box_h = 12, .ofs_x = 2, .ofs_y = -2},
    {.bitmap_index = 2058, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2069, .adv_w = 128, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 2077, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2086, .adv_w = 128, .box_w = 6, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2094, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2104, .adv_w = 128, .box_w = 4, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2109, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2120, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2129, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2140, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2148, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2159, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2168, .adv_w = 128, .box_w = 7, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2178, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2189, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2197, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2208, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2216, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2227, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2236, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2247, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2256, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2265, .adv_w = 128, .box_w = 7, .box_h = 7, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2272, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2283, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2292, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2303, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2311, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2322, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2331, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2342, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2351, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2362, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2371, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2382, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2390, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2401, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2410, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2422, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2433, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2445, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2456, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2466, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2475, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2486, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2495, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2506, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2514, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2525, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2534, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2545, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2554, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2565, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2574, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2585, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2594, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2605, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2614, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2626, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2637, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2649, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2660, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2669, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2680, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2689, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2700, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 2709, .adv_w = 128, .box_w = 5, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2716, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2727, .adv_w = 128, .box_w = 7, .box_h = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2735, .adv_w = 128, .box_w = 8, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2747, .adv_w = 128, .box_w = 7, .box_h = 12, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 2758, .adv_w = 128, .box_w = 4, .box_h = 4, .ofs_x = 2, .ofs_y = 3},
    {.bitmap_index = 2760, .adv_w = 128, .box_w = 8, .box_h = 9, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {.range_start = 32, .range_length = 95, .glyph_id_start = 1,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 160, .range_length = 224, .glyph_id_start = 96,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 536, .range_length = 4, .glyph_id_start = 320,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8226, .range_length = 1, .glyph_id_start = 324,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
    {.range_start = 8364, .range_length = 1, .glyph_id_start = 325,
     .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 5,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t lv_font_eink_bold_14 = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 16,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = &lv_font_eink_symbols_14,
    .user_data = NULL,
};
