#!/usr/bin/env python3
# Regenerates src/fonts/emoji_font.h — the monochrome Noto Emoji face used as the
# LVGL fallback font for full emoji rendering (see main_lvgl.cpp emoji plumbing).
#
# Source: Noto Emoji (SIL OFL 1.1), google/fonts ofl/notoemoji/NotoEmoji[wght].ttf
# Steps: instance the variable font at wght=400, subset to its emoji cmap, drop
# layout/hint tables stb_truetype can't use, emit as a flash-resident C array.
#
# Usage: python3 tools/gen_emoji_font.py path/to/NotoEmoji[wght].ttf
import sys, os
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

src = sys.argv[1]
out = os.path.join(os.path.dirname(__file__), "..", "src", "fonts", "emoji_font.h")

f = TTFont(src)
if "fvar" in f:
    instantiateVariableFont(f, {"wght": 400}, inplace=True)
cps = sorted(f.getBestCmap().keys())

opts = subset.Options()
opts.drop_tables += ['GSUB','GPOS','GDEF','morx','kern','FFTM','MATH']
opts.layout_features = []
opts.name_IDs = []
opts.glyph_names = False
opts.hinting = False
opts.desubroutinize = True
ss = subset.Subsetter(options=opts)
ss.populate(unicodes=cps)
ss.subset(f)

import io
buf = io.BytesIO(); f.save(buf); data = buf.getvalue()

with open(out, "w") as h:
    h.write("// Auto-generated by tools/gen_emoji_font.py. Do not hand-edit.\n")
    h.write("// Noto Emoji (SIL OFL 1.1), monochrome, wght=400, emoji cmap only.\n")
    h.write("// Rendered at runtime by lv_tiny_ttf as the Montserrat fallback font.\n")
    h.write("#pragma once\n#include <stdint.h>\n\n")
    h.write(f"// {len(cps)} emoji codepoints, {len(data)} bytes\n")
    h.write("const uint8_t kEmojiFontData[] = {\n")
    for i in range(0, len(data), 20):
        h.write("  " + ",".join(str(b) for b in data[i:i+20]) + ",\n")
    h.write("};\n")
    h.write(f"const unsigned kEmojiFontDataLen = {len(data)}u;\n")
print("wrote", out, len(data), "bytes,", len(cps), "codepoints")
