"""Compiles lang/*.lang into src/i18n_builtin.h for TR() (issue #99).

A .lang file is wadamesh's format: `#` comment/header lines, then one
translation per line as `English<TAB>translation`, with \\n, \\t and \\\\ escaped
in both halves. The English is the key TR() looks up, exactly as it appears in
the source (after escapes are undone). Lines without a tab, and pairs whose
translation is empty, are skipped -- an untranslated string falls back to the
English anyway.

Emitted per language as a table sorted by the key's UTF-8 bytes, which is the
order strcmp() compares in, so TR() can binary-search it.

Runs as a PlatformIO pre: script on every build and rewrites the header only
when its content changes, so an unchanged tree does not force a rebuild. Also
runnable by hand:  python3 tools/gen_lang_builtin.py

Reads:  lang/<code>.lang for every code in LANGS but "en"
Writes: src/i18n_builtin.h (gitignored)
"""
import os
import sys

try:
    Import("env")  # noqa: F821 -- injected by PlatformIO
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Same order as enum UiLang in src/i18n.h -- the index is what gets stored.
# English is the keys themselves and has no file.
LANGS = ["en", "es", "fr", "ro", "it"]

LANG_DIR = os.path.join(PROJECT_DIR, "lang")
DST_PATH = os.path.join(PROJECT_DIR, "src", "i18n_builtin.h")


def unescape(s):
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            out.append({"n": "\n", "t": "\t", "\\": "\\"}.get(n, "\\" + n))
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def c_literal(s):
    # UTF-8 goes into the source as-is: the compilers here take UTF-8 source,
    # and it keeps the table readable. Only what C needs escaped is.
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return '"' + s + '"'


def load(code):
    path = os.path.join(LANG_DIR, code + ".lang")
    pairs = {}
    if not os.path.isfile(path):
        return pairs
    with open(path, "r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.rstrip("\n").rstrip("\r")
            if not line or line.startswith("#") or "\t" not in line:
                continue
            key, val = line.split("\t", 1)
            key, val = unescape(key), unescape(val)
            if not key or not val:
                continue
            if key in pairs and pairs[key] != val:
                sys.exit(f"{path}:{lineno}: duplicate key with a different translation: {key!r}")
            pairs[key] = val
    return pairs


def render():
    lines = [
        "// Generated by tools/gen_lang_builtin.py from lang/*.lang -- do not edit.",
        "#pragma once",
        '#include "i18n.h"',
        "",
        "struct I18nPair {",
        "    const char *key;",
        "    const char *val;",
        "};",
        "",
    ]
    names = []
    counts = []
    for code in LANGS:
        if code == "en":
            names.append("nullptr")
            counts.append("0")
            continue
        pairs = load(code)
        ident = "kLang_" + code.replace("-", "_")
        if not pairs:
            names.append("nullptr")
            counts.append("0")
            continue
        lines.append(f"static const I18nPair {ident}[] = {{")
        for key in sorted(pairs, key=lambda k: k.encode("utf-8")):
            lines.append(f"    {{ {c_literal(key)}, {c_literal(pairs[key])} }},")
        lines.append("};")
        lines.append("")
        names.append(ident)
        counts.append(str(len(pairs)))
    lines.append(f"static const I18nPair *const kBuiltinLang[LANG_COUNT] = {{ {', '.join(names)} }};")
    lines.append(f"static const int kBuiltinLangCount[LANG_COUNT] = {{ {', '.join(counts)} }};")
    lines.append("")
    return "\n".join(lines)


def main():
    text = render()
    old = None
    if os.path.isfile(DST_PATH):
        with open(DST_PATH, "r", encoding="utf-8") as fh:
            old = fh.read()
    if old != text:
        with open(DST_PATH, "w", encoding="utf-8") as fh:
            fh.write(text)


main()
