#!/usr/bin/env bash
# Regenerates src/fonts/latin/lv_font_montserrat_<N>.c -- LVGL's built-in
# Montserrat faces, cut again with the Latin letters the built-ins leave out
# (issue #99, phase 0).
#
# LVGL 9.5's built-ins carry ASCII 0x20-0x7F plus degree and bullet, so every
# accented letter (a with acute, n with tilde, inverted ? and !, ...) drew as a
# missing-glyph box -- in received messages and node names, before any
# translation. These are the same faces, from the same Montserrat-Medium.ttf and
# FontAwesome file LVGL ships, with the same options and the same symbol list,
# and one wider text range:
#
#   0x20-0x7F    ASCII (as before)
#   0xA0-0x17F   Latin-1 Supplement + Latin Extended-A: Spanish, Portuguese,
#                French, German, Italian, Romanian, Czech, Hungarian, ...
#                (degree 0xB0 is inside it)
#   0x218-0x21B  S/T with comma below: Romanian's correct letters (the cedilla
#                forms in Extended-A are the old substitutes)
#   0x2022       bullet (as before)
#   0x20AC       euro sign
#
# They keep the built-ins' symbol names (lv_font_montserrat_<N>), so every
# &lv_font_montserrat_<N> in the source resolves to them; lv_conf.h turns the
# LVGL copies off and declares these through LV_FONT_CUSTOM_DECLARE.
#
# Needs node (npx fetches lv_font_conv@1.5.3) and an LVGL checkout under
# .pio/libdeps for the source fonts -- any env's copy will do.
#
#   tools/gen_latin_fonts.sh            # every size
#   tools/gen_latin_fonts.sh 14 16      # just these
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/fonts/latin"
SRC="$(ls -d "$ROOT"/.pio/libdeps/*/lvgl/scripts/built_in_font 2>/dev/null | head -1 || true)"
if [[ -z "$SRC" ]]; then
  echo "No LVGL checkout under .pio/libdeps; run a build once first." >&2
  exit 1
fi

TEXT_RANGE="0x20-0x7F,0xA0-0x17F,0x218-0x21B,0x2022,0x20AC"
# LVGL 9.5's built-in symbol set (LV_SYMBOL_*), copied from the Opts line of its
# own lv_font_montserrat_*.c -- identical at every size.
SYMBOLS="61441,61448,61451,61452,61452,61453,61457,61459,61461,61465,61468,61473,61478,61479,61480,61502,61507,61512,61515,61516,61517,61521,61522,61523,61524,61543,61544,61550,61552,61553,61556,61559,61560,61561,61563,61587,61589,61636,61637,61639,61641,61664,61671,61674,61683,61724,61732,61787,61931,62016,62017,62018,62019,62020,62087,62099,62212,62189,62810,63426,63650"

SIZES=("$@")
if [[ ${#SIZES[@]} -eq 0 ]]; then
  # Every size lv_conf.h enables on any board (20 is the P4's alone).
  SIZES=(10 12 14 16 18 20 24 28 32 40)
fi

mkdir -p "$OUT"
cd "$SRC"
for N in "${SIZES[@]}"; do
  F="$OUT/lv_font_montserrat_${N}.c"
  npx --yes lv_font_conv@1.5.3 --no-compress --no-prefilter --bpp 4 --size "$N" \
    --font Montserrat-Medium.ttf -r "$TEXT_RANGE" \
    --font FontAwesome5-Solid+Brands+Regular.woff -r "$SYMBOLS" \
    --format lvgl -o "$F" --force-fast-kern-format
  # 1. The generator's include block assumes LVGL's own tree; <lvgl.h> is what
  #    this project includes everywhere else.
  # 2. Its guard is LV_FONT_MONTSERRAT_<N> -- the very switch lv_conf.h turns
  #    off to drop LVGL's copy. Left alone, this file would compile to nothing.
  # 3. Line height and baseline are copied from LVGL's own face of this size.
  #    The wider range raises both (accented capitals reach higher, cedillas
  #    and ogoneks lower: 14 px would go from 16/3 to 19/4), and every layout
  #    here is tuned to the built-in metrics -- a taller line box on every
  #    label of every board would move all of them. Kept as they were, an
  #    accent on a capital or a tail below can lose a pixel or two at a
  #    label's outer edge; lowercase accents fit inside the ascender anyway.
  python3 - "$F" "$N" "$ROOT/.pio/libdeps" <<'PY'
import glob, re, sys
path, n, libdeps = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(path, encoding="utf-8").read()
ref = sorted(glob.glob(f"{libdeps}/*/lvgl/src/font/lv_font_montserrat_{n}.c"))
if not ref:
    sys.exit(f"no LVGL lv_font_montserrat_{n}.c to take metrics from")
r = open(ref[0], encoding="utf-8").read()
lh = re.search(r"\.line_height = (\d+)", r).group(1)
bl = re.search(r"\.base_line = (\d+)", r).group(1)
s = re.sub(r"\.line_height = \d+", f".line_height = {lh}", s, count=1)
s = re.sub(r"\.base_line = \d+", f".base_line = {bl}", s, count=1)
s = re.sub(r'#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n#include "lvgl.h"\n#else\n#include "[^"]*"\n#endif',
           '#include <lvgl.h>', s)
s = s.replace(f"LV_FONT_MONTSERRAT_{n}", f"CAMILLIA_LATIN_MONTSERRAT_{n}")
banner = ("/* Generated by tools/gen_latin_fonts.sh (issue #99) -- do not edit.\n"
          f" * LVGL's built-in Montserrat {n} plus Latin-1/Extended-A and the euro sign,\n"
          f" * with LVGL's line metrics ({lh}/{bl}) kept;\n"
          " * replaces the LVGL copy under the same name (see lv_conf.h). */\n\n")
open(path, "w", encoding="utf-8").write(banner + s)
PY
  echo "wrote $F"
done
